#!/usr/bin/env python3
"""Embeds a Nova PE (produced by `nova build`) into an NTASM data include.

The kernel loads the program with the same layout the Nova ABI2 host uses:
text at base+0, then at the next page an 8-byte anchor followed by rdata,
then data at the next page. Since compiled Nova addresses its rdata/data
rip-relative to those exact offsets, replicating the layout runs the code at
any base with no relocations. This script pulls the .text, .rdata and .data
sections out of the PE and emits them plus the entry offset.
"""
import struct
import sys
from pathlib import Path


def sections(pe):
    e_lfanew = struct.unpack_from("<I", pe, 0x3C)[0]
    assert pe[e_lfanew:e_lfanew + 4] == b"PE\0\0"
    coff = e_lfanew + 4
    num_sections = struct.unpack_from("<H", pe, coff + 2)[0]
    opt_size = struct.unpack_from("<H", pe, coff + 16)[0]
    opt = coff + 20
    entry_rva = struct.unpack_from("<I", pe, opt + 16)[0]
    table = opt + opt_size
    out = {}
    for i in range(num_sections):
        base = table + i * 40
        name = pe[base:base + 8].rstrip(b"\0").decode()
        vsize, vaddr, rawsize, rawptr = struct.unpack_from("<IIII", pe, base + 8)
        out[name] = (vaddr, pe[rawptr:rawptr + rawsize])
    return entry_rva, out


def literal(data):
    return '"' + "".join(chr(b) if 32 <= b < 127 and b not in (34, 92)
                         else f"\\x{b:02x}" for b in data) + '"'


def main():
    pe = Path(sys.argv[1]).read_bytes()
    out = Path(sys.argv[2])
    entry_rva, sec = sections(pe)
    text_rva = sec[".text"][0]
    text = sec[".text"][1]
    rdata = sec.get(".rdata", (0, b""))[1]   # already begins with the anchor
    data = sec.get(".data", (0, b""))[1]
    entry = entry_rva - text_rva
    lines = [
        "// Generated by tools/embed_nova.py from a `nova build` PE.",
        f"%define NOVA_TEXT_LEN {len(text)}",
        f"%define NOVA_RDATA_LEN {len(rdata)}",
        f"%define NOVA_DATA_LEN {len(data)}",
        f"%define NOVA_ENTRY {entry}",
        "section .rdata {",
        f"    data novaapp_text:array<u8,{len(text)}> = {literal(text)}",
        f"    data novaapp_rdata:array<u8,{max(1,len(rdata))}> = {literal(rdata or bytes(1))}",
        f"    data novaapp_data:array<u8,{max(1,len(data))}> = {literal(data or bytes(1))}",
        "}",
    ]
    out.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
