#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;static const uint64_t guard=UINT64_C(0xcccccccccccccccc);
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static char*loadf(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime,out[4];}Run;static Run run(const NovaHostImage*i,const char*s,uint64_t words){Run r={.out={guard,guard,guard,guard}};NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t sh=nova_borrow_v2(&c,(void*)s,strlen(s),0),oh=nova_borrow_v2(&c,r.out,words*8,1);uint64_t a[]={sh,strlen(s),oh,words};r.returned=i->entry(&c,a,4);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void ok(const NovaHostImage*i,const char*n,const char*s,uint64_t b,uint64_t e,uint64_t m){Run r=run(i,s,4);cases++;checks++;if(r.returned||r.runtime||r.out[0]!=b||r.out[1]!=e||r.out[2]!=m||r.out[3]){failures++;fprintf(stderr,"FAIL ok %s ret=%llu out=%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2]);}}
static void err(const NovaHostImage*i,const char*n,const char*s,uint64_t code,uint64_t a,uint64_t b){Run r=run(i,s,4);cases++;checks++;if(r.returned!=code||r.runtime||r.out[0]==guard||r.out[1]==guard||r.out[2]!=a||r.out[3]!=b){failures++;fprintf(stderr,"FAIL err %s ret=%llu out=%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
static void bad(const NovaHostImage*i,const char*n,const char*s,uint64_t words){Run r=run(i,s,words);cases++;checks++;if(r.returned!=800||r.runtime||r.out[0]!=guard||r.out[1]!=guard){failures++;fprintf(stderr,"FAIL invalid %s\n",n);}}
#define HEAD "module m\ntarget x86_64-nexora-none\n"
#define FULL "versions {\nntir 0.1\nmachine_ir 0.1\nsections 0.1\nsymbols 0.1\nrelocations 0.1\nnxo 0.1\n}\n"
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/versions-entry.nova","toolchain/ntasm-nova/versions.nova","toolchain/ntasm-nova/parser.nova","toolchain/ntasm-nova/ast.nova","toolchain/ntasm-nova/lexer.nova"};char*sources[5]={0};NtFInput inputs[5];for(unsigned i=0;i<5;i++){size_t n=0;sources[i]=loadf(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=1;for(unsigned i=0;i<5;i++)if(!sources[i])all=0;CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,5,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){ok(&image,"none",HEAD,0,0,0);ok(&image,"full",HEAD FULL,1,6,63);const char*unknown=HEAD "versions {\nfoo 0.1\n}\n";err(&image,"unknown",unknown,347,1,0);const char*duplicate=HEAD "versions {\nntir 0.1\nntir 0.1\n}\n";err(&image,"duplicate",duplicate,347,2,0);const char*wrong=HEAD "versions {\nntir 1.0\nmachine_ir 0.1\nsections 0.1\nsymbols 0.1\nrelocations 0.1\nnxo 0.1\n}\n";err(&image,"wrong",wrong,348,1,0);const char*incomplete=HEAD "versions {\nntir 0.1\n}\n";err(&image,"incomplete",incomplete,349,1,0);bad(&image,"short",HEAD,3);bad(&image,"invalid","target x86_64-nexora-none\n",4);}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<5;i++)free(sources[i]);printf("NTASM_NOVA_VERSIONS checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
