#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include "x64.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;static const uint8_t guard=0xcc;
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static char*loadf(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime;uint8_t out[160];}Run;static Run run(const NovaHostImage*i,const char*source,uint64_t words){Run r;memset(&r,0,sizeof r);memset(r.out,guard,sizeof r.out);NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t sh=nova_borrow_v2(&c,(void*)source,strlen(source),0),oh=nova_borrow_v2(&c,r.out,words,1);uint64_t a[]={sh,strlen(source),1,3,oh,words};r.returned=i->entry(&c,a,6);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static size_t encode_(uint8_t*out,const char*name,NtX64Operand*operands,size_t count){NtX64Instruction e={0};NtX64Context c={1,3};CHECK(nt_x64_encode(name,operands,count,c,&e)==0,"oracle encode");memcpy(out,e.bytes,e.length);return e.length;}
static void unified(const NovaHostImage*i){const char*source="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nstart:\nmov rax,rbx\nadd rax,1\nload r8,[r12+rcx*4+8]:ptr<user,u64>\nje done\nsub r8,r9\njmp start\ndone:\nstore [fs:r13-128]:ptr<kernel,u32>,eax\nreturn 0\n}\n}\n";uint8_t expected[159]={0},sub_bytes[16]={0},store_bytes[16]={0};size_t total=0;NtX64Operand mov[2]={{.kind=NT_X64_REG,.width=64,.reg=0},{.kind=NT_X64_REG,.width=64,.reg=3}};total+=encode_(expected+total,"mov",mov,2);NtX64Operand add[2]={{.kind=NT_X64_REG,.width=64,.reg=0},{.kind=NT_X64_IMM,.imm=1}};total+=encode_(expected+total,"add",add,2);NtX64Operand load[2]={{.kind=NT_X64_REG,.width=64,.reg=8},{.kind=NT_X64_MEM,.width=64,.base=12,.index=1,.scale=4,.disp=8}};total+=encode_(expected+total,"mov",load,2);NtX64Operand sub[2]={{.kind=NT_X64_REG,.width=64,.reg=8},{.kind=NT_X64_REG,.width=64,.reg=9}};size_t sub_len=encode_(sub_bytes,"sub",sub,2);NtX64Operand store[2]={{.kind=NT_X64_MEM,.width=32,.base=13,.index=-1,.scale=1,.disp=-128,.segment=NT_X64_FS},{.kind=NT_X64_REG,.width=32,.reg=0}};size_t store_len=encode_(store_bytes,"mov",store,2);NtX64Operand je={.kind=NT_X64_REL,.imm=sub_len+5,.is_signed=1};total+=encode_(expected+total,"je",&je,1);memcpy(expected+total,sub_bytes,sub_len);total+=sub_len;uint64_t next=total+5;NtX64Operand jmp={.kind=NT_X64_REL,.imm=UINT64_MAX-next+1,.is_signed=1};total+=encode_(expected+total,"jmp",&jmp,1);memcpy(expected+total,store_bytes,store_len);total+=store_len;Run r=run(i,source,sizeof r.out);cases++;CHECK(r.returned==0&&r.runtime==0&&r.out[0]==total&&!memcmp(r.out+1,expected,total),"unified two-pass lowering");Run short_=run(i,source,8);cases++;int untouched=short_.returned==800&&!short_.runtime;for(unsigned k=0;k<8;k++)untouched&=short_.out[k]==guard;CHECK(untouched,"unified short transactional");}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/x64-lower-unified-entry.nova","toolchain/ntasm-nova/x64_lower_control.nova","toolchain/ntasm-nova/x64_lower_fixed.nova","toolchain/ntasm-nova/x64_fixed.nova","toolchain/ntasm-nova/register_widths.nova","toolchain/ntasm-nova/parser.nova","toolchain/ntasm-nova/ast.nova","toolchain/ntasm-nova/lexer.nova"};char*sources[8]={0};NtFInput inputs[8];for(unsigned i=0;i<8;i++){size_t n=0;sources[i]=loadf(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=1;for(unsigned i=0;i<8;i++)if(!sources[i])all=0;CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,8,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory)unified(&image);if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<8;i++)free(sources[i]);printf("NTASM_NOVA_X64_LOWER_UNIFIED checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
