#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include "x64.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static const uint8_t guard=0xcc;
static char*loadf(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime;uint8_t out[16];}Run;
static Run run(const NovaHostImage*i,const char*name,uint64_t count,uint64_t destination,uint64_t width,uint64_t immediate,uint64_t is_signed,uint64_t features,uint64_t cpl,uint64_t words){Run r;memset(&r,0,sizeof r);memset(r.out,guard,sizeof r.out);NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t nh=nova_borrow_v2(&c,(void*)name,strlen(name),0),oh=nova_borrow_v2(&c,r.out,words,1);uint64_t a[]={nh,strlen(name),count,destination,width,immediate,is_signed,features,cpl,oh,words};r.returned=i->entry(&c,a,11);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void compare(const NovaHostImage*i,const char*name,uint64_t count,uint64_t destination,uint64_t width,uint64_t immediate,uint64_t is_signed,uint64_t features,uint64_t cpl){NtX64Operand operands[2]={{.kind=NT_X64_REG,.width=(unsigned)width,.reg=(unsigned)destination},{.kind=NT_X64_IMM,.imm=immediate,.is_signed=(unsigned)is_signed}};NtX64Instruction expected={0};NtX64Context context={(uint32_t)features,(unsigned)cpl};NtX64Error e=nt_x64_encode(name,operands,(size_t)count,context,&expected);Run r=run(i,name,count,destination,width,immediate,is_signed,features,cpl,16);cases++;checks++;int bad=r.returned!=(uint64_t)e||r.runtime;if(!e){bad|=r.out[0]!=expected.length;for(unsigned k=0;k<15;k++)bad|=r.out[k+1]!=(k<expected.length?expected.bytes[k]:0);}else for(unsigned k=0;k<16;k++)bad|=r.out[k]!=guard;if(bad){failures++;fprintf(stderr,"FAIL %s c=%llu d=%llu w=%llu imm=%llu s=%llu f=%llu p=%llu ret=%llu oracle=%u\n",name,(unsigned long long)count,(unsigned long long)destination,(unsigned long long)width,(unsigned long long)immediate,(unsigned long long)is_signed,(unsigned long long)features,(unsigned long long)cpl,(unsigned long long)r.returned,(unsigned)e);}}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/x64-ri-entry.nova","toolchain/ntasm-nova/x64_fixed.nova"};char*sources[2]={0};NtFInput inputs[2];for(unsigned i=0;i<2;i++){size_t n=0;sources[i]=loadf(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=sources[0]&&sources[1];CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,2,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){const char*names[]={"mov","add","or","adc","sbb","and","sub","xor","cmp"};const uint64_t widths[]={8,16,32,64};const uint64_t registers[]={0,4,8,15};const uint64_t values[]={0,1,127,128,255,256,2147483647,2147483648,4294967295,UINT64_MAX};for(unsigned n=0;n<9;n++)for(unsigned w=0;w<4;w++)for(unsigned r=0;r<4;r++)for(unsigned v=0;v<10;v++)for(unsigned s=0;s<2;s++)compare(&image,names[n],2,registers[r],widths[w],values[v],s,1,3);for(unsigned n=0;n<9;n++){compare(&image,names[n],1,0,64,1,0,1,3);compare(&image,names[n],2,0,64,1,0,0,3);}compare(&image,"telepathy",2,0,64,1,0,1,3);compare(&image,"mov",2,16,64,1,0,1,3);compare(&image,"mov",2,0,24,1,0,1,3);compare(&image,"mov",2,0,64,1,2,1,3);compare(&image,"mov",2,0,64,1,0,1,4);Run short_=run(&image,"mov",2,0,64,1,0,1,3,15);cases++;CHECK(short_.returned==800&&short_.runtime==0&&short_.out[0]==guard&&short_.out[1]==guard,"short output transactional");}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<2;i++)free(sources[i]);printf("NTASM_NOVA_X64_RI checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
