#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;static const uint64_t guard=UINT64_C(0xcccccccccccccccc);
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static char*loadf(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime,out[4];}Run;static Run run(const NovaHostImage*i,const char*s,uint64_t words){Run r={.out={guard,guard,guard,guard}};NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t sh=nova_borrow_v2(&c,(void*)s,strlen(s),0),oh=nova_borrow_v2(&c,r.out,words*8,1);uint64_t a[]={sh,strlen(s),oh,words};r.returned=i->entry(&c,a,4);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void ok(const NovaHostImage*i,const char*n,const char*s,uint64_t c,uint64_t l,uint64_t names,uint64_t derived){Run r=run(i,s,4);cases++;checks++;if(r.returned||r.runtime||r.out[0]!=c||r.out[1]!=l||r.out[2]!=names||r.out[3]!=derived){failures++;fprintf(stderr,"FAIL %s ret=%llu runtime=%llu out=%llu,%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.runtime,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
static void err(const NovaHostImage*i,const char*n,const char*s,uint64_t code,uint64_t reason){Run r=run(i,s,4);cases++;checks++;if(r.returned!=code||r.runtime||r.out[0]==0||r.out[1]==0||r.out[2]!=reason||r.out[3]!=0){failures++;fprintf(stderr,"FAIL %s ret=%llu runtime=%llu out=%llu,%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.runtime,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
static void bad(const NovaHostImage*i,const char*n,const char*s,uint64_t words){Run r=run(i,s,words);cases++;checks++;if(r.returned!=800||r.runtime||r.out[0]!=guard||r.out[1]!=guard){failures++;fprintf(stderr,"FAIL %s ret=%llu runtime=%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.runtime);}}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/condition-types-entry.nova","toolchain/ntasm-nova/condition_types.nova","toolchain/ntasm-nova/types.nova","toolchain/ntasm-nova/parser.nova","toolchain/ntasm-nova/ast.nova","toolchain/ntasm-nova/lexer.nova"};char*sources[6]={0};NtFInput inputs[6];for(unsigned i=0;i<6;i++){size_t n=0;sources[i]=loadf(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=1;for(unsigned i=0;i<6;i++)if(!sources[i])all=0;CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,6,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){
const char*truth="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nif true {\nreturn 1\n} else {\nreturn 0\n}\n}\n}\n";ok(&image,"true",truth,1,1,0,0);
const char*param="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in ready:bool @al)->u64\neffects {}\nclobbers {} {\nif ready {\nreturn 1\n} else {\nreturn 0\n}\n}\n}\n";ok(&image,"bool param",param,1,0,1,0);
const char*local="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nlet ready:bool=false\nif ready {\nreturn 1\n} else {\nreturn 0\n}\n}\n}\n";ok(&image,"bool local",local,1,0,1,0);
const char*compare="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rcx)->u64\neffects {}\nclobbers {} {\nif x==0 {\nreturn 1\n} else {\nreturn 0\n}\n}\n}\n";ok(&image,"comparison",compare,1,0,0,1);
const char*feature="module m\ntarget x86_64-nexora-none\nfeatures {sse2}\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nif feature(sse2) {\nreturn 1\n} else {\nreturn 0\n}\n}\n}\n";ok(&image,"feature predicate",feature,1,0,0,1);
const char*integer="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nif 1 {\nreturn 1\n} else {\nreturn 0\n}\n}\n}\n";err(&image,"integer literal",integer,357,1);
const char*wrong="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rcx)->u64\neffects {}\nclobbers {} {\nif x {\nreturn 1\n} else {\nreturn 0\n}\n}\n}\n";err(&image,"integer name",wrong,357,2);
const char*arithmetic="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rcx)->u64\neffects {changes_flags}\nclobbers {} {\nif x+1 {\nreturn 1\n} else {\nreturn 0\n}\n}\n}\n";err(&image,"arithmetic unsupported",arithmetic,358,2);
const char*call="module m\ntarget x86_64-nexora-none\nsection .text {\nfn pred()->bool\neffects {}\nclobbers {} {\nreturn true\n}\nfn f()->u64\neffects {}\nclobbers {} {\nif pred() {\nreturn 1\n} else {\nreturn 0\n}\n}\n}\n";ok(&image,"bool call",call,1,0,0,1);
const char*nonbool_call="module m\ntarget x86_64-nexora-none\nsection .text {\nfn value()->u64\neffects {}\nclobbers {} {\nreturn 1\n}\nfn f()->u64\neffects {}\nclobbers {} {\nif value() {\nreturn 1\n} else {\nreturn 0\n}\n}\n}\n";err(&image,"nonbool call",nonbool_call,357,2);
bad(&image,"short",truth,3);bad(&image,"invalid","target x86_64-nexora-none\n",4);
}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<6;i++)free(sources[i]);printf("NTASM_NOVA_CONDITION_TYPES checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
