#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;static const uint64_t guard=UINT64_C(0xcccccccccccccccc);
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static char*loadf(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime,out[4];}Run;static Run run(const NovaHostImage*i,const char*s,uint64_t words){Run r={.out={guard,guard,guard,guard}};NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t sh=nova_borrow_v2(&c,(void*)s,strlen(s),0),oh=nova_borrow_v2(&c,r.out,words*8,1);uint64_t a[]={sh,strlen(s),oh,words};r.returned=i->entry(&c,a,4);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void ok(const NovaHostImage*i,const char*n,const char*s,uint64_t f,uint64_t l,uint64_t v){Run r=run(i,s,4);cases++;checks++;if(r.returned||r.runtime||r.out[0]!=f||r.out[1]!=l||r.out[2]!=v||r.out[3]){failures++;fprintf(stderr,"FAIL ok %s ret=%llu out=%llu,%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
static void err(const NovaHostImage*i,const char*n,const char*s,uint64_t code,uint64_t bit){Run r=run(i,s,4);cases++;checks++;if(r.returned!=code||r.runtime||r.out[0]==guard||r.out[1]==guard||(code==335&&(r.out[2]!=1||r.out[3]!=bit))){failures++;fprintf(stderr,"FAIL err %s ret=%llu out=%llu,%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
static void bad(const NovaHostImage*i,const char*n,const char*s,uint64_t words){Run r=run(i,s,words);cases++;checks++;if(r.returned!=800||r.runtime||r.out[0]!=guard||r.out[1]!=guard){failures++;fprintf(stderr,"FAIL invalid %s\n",n);}}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/body-clobbers-entry.nova","toolchain/ntasm-nova/body_clobbers.nova","toolchain/ntasm-nova/clobbers.nova","toolchain/ntasm-nova/register_widths.nova","toolchain/ntasm-nova/callable_names.nova","toolchain/ntasm-nova/semantics.nova","toolchain/ntasm-nova/parser.nova","toolchain/ntasm-nova/ast.nova","toolchain/ntasm-nova/lexer.nova"};char*sources[9]={0};NtFInput inputs[9];for(unsigned i=0;i<9;i++){size_t n=0;sources[i]=loadf(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=1;for(unsigned i=0;i<9;i++)if(!sources[i])all=0;CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,9,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){
const char*none="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nreturn 0\n}\n}\n";ok(&image,"none",none,1,0,0);
const char*rax="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<user,u64> @rdi)->u64\neffects {reads_mem(user)}\nclobbers {rax} {\nload rax,[p]:ptr<user,u64>\nreturn rax\n}\n}\n";ok(&image,"rax",rax,1,1,1);
const char*alias="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<user,u64> @rdi)->u64\neffects {reads_mem(user)}\nclobbers {eax} {\nload rax,[p]:ptr<user,u64>\nreturn rax\n}\n}\n";ok(&image,"alias",alias,1,1,1);
const char*missing="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<user,u64> @rdi)->u64\neffects {reads_mem(user)}\nclobbers {} {\nload rax,[p]:ptr<user,u64>\nreturn rax\n}\n}\n";err(&image,"missing",missing,335,1);
const char*r10="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<user,u64> @rdi)->u64\neffects {reads_mem(user)}\nclobbers {r10d} {\nload r10,[p]:ptr<user,u64>\nreturn r10\n}\n}\n";ok(&image,"r10",r10,1,1,1);
const char*unknown="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<user,u64> @rdi)->u64\neffects {reads_mem(user)}\nclobbers {} {\nload foo,[p]:ptr<user,u64>\nreturn 0\n}\n}\n";err(&image,"unknown",unknown,336,0);
const char*store="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<user,u64> @rdi,in v:u64 @rax)->u64\neffects {writes_mem(user)}\nclobbers {} {\nstore [p]:ptr<user,u64>,rax\nreturn 0\n}\n}\n";ok(&image,"store ignored",store,1,0,0);
const char*separate="module m\ntarget x86_64-nexora-none\nsection .text {\nfn a(in p:ptr<user,u64> @rdi)->u64\neffects {reads_mem(user)}\nclobbers {rax} {\nload rax,[p]:ptr<user,u64>\nreturn rax\n}\nfn b(in p:ptr<kernel,u64> @rdi)->u64\neffects {reads_mem(kernel)}\nclobbers {rdx} {\nload rdx,[p]:ptr<kernel,u64>\nreturn rdx\n}\n}\n";ok(&image,"separate",separate,2,2,2);
const char*rdtsc="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {reads_clock}\nclobbers {rax,rdx} {\nrdtsc\nreturn 0\n}\n}\n";ok(&image,"rdtsc",rdtsc,1,1,1);
const char*rdtsc_missing="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {reads_clock}\nclobbers {rax} {\nrdtsc\nreturn 0\n}\n}\n";err(&image,"rdtsc missing",rdtsc_missing,335,4);
const char*cpuid="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {eax,ebx,ecx,edx} {\ncpuid\nreturn 0\n}\n}\n";ok(&image,"cpuid",cpuid,1,1,1);
const char*syscall="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {control,changes_flags}\nclobbers {rcx,r11} {\nsyscall\nreturn 0\n}\n}\n";ok(&image,"syscall",syscall,1,1,1);
const char*syscall_missing="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {control,changes_flags}\nclobbers {rcx} {\nsyscall\nreturn 0\n}\n}\n";err(&image,"syscall missing",syscall_missing,335,2048);
const char*iret="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->never\neffects {privileged,changes_flags,control,no_return}\nclobbers {rsp} {\niretq\n}\n}\n";ok(&image,"iret",iret,1,1,1);
const char*mov="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rbx)->u64\neffects {}\nclobbers {eax} {\nmov rax,rbx\nreturn rax\n}\n}\n";ok(&image,"mov",mov,1,1,1);
const char*mov_missing="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rbx)->u64\neffects {}\nclobbers {} {\nmov rax,rbx\nreturn rax\n}\n}\n";err(&image,"mov missing",mov_missing,335,1);
const char*add="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rax)->u64\neffects {changes_flags}\nclobbers {r10d} {\nadd r10,rax\nreturn r10\n}\n}\n";ok(&image,"add",add,1,1,1);
const char*compare="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rax,in y:u64 @rbx)->u64\neffects {changes_flags}\nclobbers {} {\ncmp rax,rbx\nreturn 0\n}\n}\n";ok(&image,"cmp ignored",compare,1,0,0);
const char*xchg="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rax,in y:u64 @rcx)->u64\neffects {}\nclobbers {eax,ecx} {\nxchg rax,rcx\nreturn rax\n}\n}\n";ok(&image,"xchg",xchg,1,1,1);
const char*xchg_missing="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rax,in y:u64 @rcx)->u64\neffects {}\nclobbers {rax} {\nxchg rax,rcx\nreturn rax\n}\n}\n";err(&image,"xchg missing",xchg_missing,335,2);
bad(&image,"short",none,3);bad(&image,"invalid","target x86_64-nexora-none\n",4);
}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<9;i++)free(sources[i]);printf("NTASM_NOVA_BODY_CLOBBERS checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
