#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include "x64.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static const uint8_t guard=0xcc;
static char*loadf(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime;uint8_t out[32];}Run;
static Run run(const NovaHostImage*i,const char*source,uint64_t features,uint64_t cpl,uint64_t words){Run r;memset(&r,0,sizeof r);memset(r.out,guard,sizeof r.out);NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t sh=nova_borrow_v2(&c,(void*)source,strlen(source),0),oh=nova_borrow_v2(&c,r.out,words,1);uint64_t a[]={sh,strlen(source),features,cpl,oh,words};r.returned=i->entry(&c,a,6);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void ok(const NovaHostImage*i,const char*name,const char*source,uint64_t features,uint64_t cpl,const char**instructions,unsigned count){uint8_t expected[31]={0};size_t total=0;for(unsigned n=0;n<count;n++){NtX64Instruction encoded={0};NtX64Context context={(uint32_t)features,(unsigned)cpl};NtX64Error e=nt_x64_encode(instructions[n],NULL,0,context,&encoded);CHECK(e==0,"oracle encode");memcpy(expected+total,encoded.bytes,encoded.length);total+=encoded.length;}Run r=run(i,source,features,cpl,32);cases++;checks++;int bad=r.returned||r.runtime||r.out[0]!=total||memcmp(r.out+1,expected,total);if(bad){failures++;fprintf(stderr,"FAIL %s ret=%llu total=%u observed=%u\n",name,(unsigned long long)r.returned,(unsigned)total,r.out[0]);}}
static void err(const NovaHostImage*i,const char*name,const char*source,uint64_t features,uint64_t cpl,uint64_t code,uint64_t words){Run r=run(i,source,features,cpl,words);cases++;checks++;int bad=r.returned!=code||r.runtime;for(unsigned k=0;k<words&&k<32;k++)bad|=r.out[k]!=guard;if(bad){failures++;fprintf(stderr,"FAIL %s ret=%llu expected=%llu\n",name,(unsigned long long)r.returned,(unsigned long long)code);}}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/x64-lower-fixed-entry.nova","toolchain/ntasm-nova/x64_lower_fixed.nova","toolchain/ntasm-nova/x64_fixed.nova","toolchain/ntasm-nova/parser.nova","toolchain/ntasm-nova/ast.nova","toolchain/ntasm-nova/lexer.nova"};char*sources[6]={0};NtFInput inputs[6];for(unsigned i=0;i<6;i++){size_t n=0;sources[i]=loadf(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=1;for(unsigned i=0;i<6;i++)if(!sources[i])all=0;CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,6,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){const char*basic="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nnop\npause\nreturn 0\n}\n}\n";const char*basic_names[]={"nop","pause"};ok(&image,"basic",basic,1,3,basic_names,2);const char*system="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nrdtsc\nlfence\nreturn 0\n}\n}\n";const char*system_names[]={"rdtsc","lfence"};ok(&image,"features",system,25,0,system_names,2);const char*privileged="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nhlt\nreturn 0\n}\n}\n";err(&image,"privilege",privileged,1,3,405,32);const char*unknown="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\ntelepathy\nreturn 0\n}\n}\n";err(&image,"unknown",unknown,1,3,401,32);const char*operands="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nmov rax,rbx\nreturn 0\n}\n}\n";err(&image,"operand form",operands,1,3,409,32);err(&image,"short",basic,1,3,800,2);err(&image,"invalid","target x86_64-nexora-none\n",1,3,800,32);}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<6;i++)free(sources[i]);printf("NTASM_NOVA_X64_LOWER_FIXED checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
