#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include "x64.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;static const uint8_t guard=0xcc;
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static char*loadf(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime;uint8_t out[128];}Run;static Run run(const NovaHostImage*i,const char*source,uint64_t words){Run r;memset(&r,0,sizeof r);memset(r.out,guard,sizeof r.out);NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t sh=nova_borrow_v2(&c,(void*)source,strlen(source),0),oh=nova_borrow_v2(&c,r.out,words,1);uint64_t a[]={sh,strlen(source),1,3,oh,words};r.returned=i->entry(&c,a,6);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void success(const NovaHostImage*i){const char*source="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nstart:\nnop\nje done\npause\njmp start\ndone:\nud2\nreturn 0\n}\n}\n";uint8_t expected[127]={0};size_t total=0;NtX64Instruction e={0};NtX64Context c={1,3};CHECK(nt_x64_encode("nop",NULL,0,c,&e)==0,"nop oracle");memcpy(expected+total,e.bytes,e.length);total+=e.length;NtX64Operand forward={.kind=NT_X64_REL,.imm=7,.is_signed=1};e=(NtX64Instruction){0};CHECK(nt_x64_encode("je",&forward,1,c,&e)==0,"je oracle");memcpy(expected+total,e.bytes,e.length);total+=e.length;e=(NtX64Instruction){0};CHECK(nt_x64_encode("pause",NULL,0,c,&e)==0,"pause oracle");memcpy(expected+total,e.bytes,e.length);total+=e.length;NtX64Operand backward={.kind=NT_X64_REL,.imm=UINT64_MAX-13,.is_signed=1};e=(NtX64Instruction){0};CHECK(nt_x64_encode("jmp",&backward,1,c,&e)==0,"jmp oracle");memcpy(expected+total,e.bytes,e.length);total+=e.length;e=(NtX64Instruction){0};CHECK(nt_x64_encode("ud2",NULL,0,c,&e)==0,"ud2 oracle");memcpy(expected+total,e.bytes,e.length);total+=e.length;Run r=run(i,source,sizeof r.out);cases++;CHECK(r.returned==0&&r.runtime==0&&r.out[0]==total&&!memcmp(r.out+1,expected,total),"two-pass labels");}
static void error_(const NovaHostImage*i,const char*name,const char*source,uint64_t code){Run r=run(i,source,sizeof r.out);cases++;int bad=r.returned!=code||r.runtime;for(unsigned k=0;k<sizeof r.out;k++)bad|=r.out[k]!=guard;CHECK(!bad,name);}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/x64-labels-entry.nova","toolchain/ntasm-nova/x64_lower_control.nova","toolchain/ntasm-nova/x64_lower_fixed.nova","toolchain/ntasm-nova/x64_fixed.nova","toolchain/ntasm-nova/register_widths.nova","toolchain/ntasm-nova/parser.nova","toolchain/ntasm-nova/ast.nova","toolchain/ntasm-nova/lexer.nova"};char*sources[8]={0};NtFInput inputs[8];for(unsigned i=0;i<8;i++){size_t n=0;sources[i]=loadf(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=1;for(unsigned i=0;i<8;i++)if(!sources[i])all=0;CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,8,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){success(&image);const char*duplicate="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nx:\nnop\nx:\nnop\nreturn 0\n}\n}\n";error_(&image,"duplicate",duplicate,820);const char*missing="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\njmp absent\nreturn 0\n}\n}\n";error_(&image,"missing",missing,821);const char*badtarget="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nje 1\nreturn 0\n}\n}\n";error_(&image,"target form",badtarget,409);}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<8;i++)free(sources[i]);printf("NTASM_NOVA_X64_LABELS checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
