#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include "x64.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static const uint8_t guard=0xcc;
static char*loadf(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime;uint8_t out[96];}Run;
static Run run(const NovaHostImage*i,const char*source){Run r;memset(&r,0,sizeof r);memset(r.out,guard,sizeof r.out);NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t sh=nova_borrow_v2(&c,(void*)source,strlen(source),0),oh=nova_borrow_v2(&c,r.out,sizeof r.out,1);uint64_t a[]={sh,strlen(source),1,3,oh,sizeof r.out};r.returned=i->entry(&c,a,6);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void append(uint8_t*out,size_t*total,NtX64Operand*operands){NtX64Instruction encoded={0};NtX64Context context={1,3};CHECK(nt_x64_encode("mov",operands,2,context,&encoded)==0,"oracle mov SIB");memcpy(out+*total,encoded.bytes,encoded.length);*total+=encoded.length;}
static void success(const NovaHostImage*i){const char*source="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nload rax,[rbx+rcx*2+8]:ptr<user,u64>\nstore [r12+r13*8-128]:ptr<kernel,u32>,r9d\nmov r8w,[rbp+r14]:ptr<user,u16>\nreturn 0\n}\n}\n";uint8_t expected[95]={0};size_t total=0;NtX64Operand a[2]={{.kind=NT_X64_REG,.width=64,.reg=0},{.kind=NT_X64_MEM,.width=64,.base=3,.index=1,.scale=2,.disp=8}};append(expected,&total,a);NtX64Operand b[2]={{.kind=NT_X64_MEM,.width=32,.base=12,.index=13,.scale=8,.disp=-128},{.kind=NT_X64_REG,.width=32,.reg=9}};append(expected,&total,b);NtX64Operand c[2]={{.kind=NT_X64_REG,.width=16,.reg=8},{.kind=NT_X64_MEM,.width=16,.base=5,.index=14,.scale=1}};append(expected,&total,c);Run r=run(i,source);cases++;CHECK(r.returned==0&&r.runtime==0&&r.out[0]==total&&!memcmp(r.out+1,expected,total),"SIB AST lowering");}
static void error_(const NovaHostImage*i,const char*name,const char*source,uint64_t code){Run r=run(i,source);cases++;int bad=r.returned!=code||r.runtime;for(unsigned k=0;k<sizeof r.out;k++)bad|=r.out[k]!=guard;CHECK(!bad,name);}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/x64-lower-sib-entry.nova","toolchain/ntasm-nova/x64_lower_fixed.nova","toolchain/ntasm-nova/x64_fixed.nova","toolchain/ntasm-nova/register_widths.nova","toolchain/ntasm-nova/parser.nova","toolchain/ntasm-nova/ast.nova","toolchain/ntasm-nova/lexer.nova"};char*sources[7]={0};NtFInput inputs[7];for(unsigned i=0;i<7;i++){size_t n=0;sources[i]=loadf(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=1;for(unsigned i=0;i<7;i++)if(!sources[i])all=0;CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,7,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){success(&image);const char*rsp="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nload rax,[rbx+rsp*2]:ptr<user,u64>\nreturn 0\n}\n}\n";error_(&image,"rsp index",rsp,411);const char*scale="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nload rax,[rbx+rcx*3]:ptr<user,u64>\nreturn 0\n}\n}\n";error_(&image,"scale",scale,411);const char*rip="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nload rax,[rip+rcx]:ptr<user,u64>\nreturn 0\n}\n}\n";error_(&image,"rip index",rip,411);}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<7;i++)free(sources[i]);printf("NTASM_NOVA_X64_LOWER_SIB checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
