#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;static const uint64_t guard=UINT64_C(0xcccccccccccccccc);
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static char*loadf(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime,out[4];}Run;static Run run(const NovaHostImage*i,const char*s,uint64_t words){Run r={.out={guard,guard,guard,guard}};NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t sh=nova_borrow_v2(&c,(void*)s,strlen(s),0),oh=nova_borrow_v2(&c,r.out,words*8,1);uint64_t a[]={sh,strlen(s),oh,words};r.returned=i->entry(&c,a,4);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void ok(const NovaHostImage*i,const char*n,const char*s,uint64_t calls,uint64_t args,uint64_t checked){Run r=run(i,s,4);cases++;checks++;if(r.returned||r.runtime||r.out[0]!=calls||r.out[1]!=args||r.out[2]!=checked||r.out[3]){failures++;fprintf(stderr,"FAIL ok %s ret=%llu out=%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2]);}}
static void err(const NovaHostImage*i,const char*n,const char*s,uint64_t reason,uint64_t index){Run r=run(i,s,4);cases++;checks++;if(r.returned!=354||r.runtime||r.out[0]==guard||r.out[1]==guard||r.out[2]!=reason||r.out[3]!=index){failures++;fprintf(stderr,"FAIL err %s ret=%llu out=%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
static void bad(const NovaHostImage*i,const char*n,const char*s,uint64_t words){Run r=run(i,s,words);cases++;checks++;if(r.returned!=800||r.runtime||r.out[0]!=guard||r.out[1]!=guard){failures++;fprintf(stderr,"FAIL invalid %s\n",n);}}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/call-types-entry.nova","toolchain/ntasm-nova/call_types.nova","toolchain/ntasm-nova/initializer_types.nova","toolchain/ntasm-nova/calls.nova","toolchain/ntasm-nova/refs.nova","toolchain/ntasm-nova/types.nova","toolchain/ntasm-nova/callable_names.nova","toolchain/ntasm-nova/semantics.nova","toolchain/ntasm-nova/parser.nova","toolchain/ntasm-nova/ast.nova","toolchain/ntasm-nova/lexer.nova"};char*sources[11]={0};NtFInput inputs[11];for(unsigned i=0;i<11;i++){size_t n=0;sources[i]=loadf(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=1;for(unsigned i=0;i<11;i++)if(!sources[i])all=0;CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,11,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){
const char*literal="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in x:u8 @al)->u8\neffects {}\nclobbers {} {\nreturn x\n}\nfn f()->u64\neffects {}\nclobbers {} {\ncall g(255)\nreturn 0\n}\n}\n";ok(&image,"literal",literal,1,1,1);
const char*range="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in x:u8 @al)->u8\neffects {}\nclobbers {} {\nreturn x\n}\nfn f()->u64\neffects {}\nclobbers {} {\ncall g(256)\nreturn 0\n}\n}\n";err(&image,"range",range,2,0);
const char*param="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in x:u32 @edi)->u32\neffects {}\nclobbers {} {\nreturn x\n}\nfn f(in y:u32 @edi)->u64\neffects {}\nclobbers {} {\ncall g(y)\nreturn 0\n}\n}\n";ok(&image,"param",param,1,1,1);
const char*param_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in x:u64 @rdi)->u64\neffects {}\nclobbers {} {\nreturn x\n}\nfn f(in y:u32 @edi)->u64\neffects {}\nclobbers {} {\ncall g(y)\nreturn 0\n}\n}\n";err(&image,"param mismatch",param_bad,1,0);
const char*local="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in x:u16 @di)->u16\neffects {}\nclobbers {} {\nreturn x\n}\nfn f()->u64\neffects {}\nclobbers {} {\nlet y:u16=1\ncall g(y)\nreturn 0\n}\n}\n";ok(&image,"local",local,1,1,1);
const char*nested="module m\ntarget x86_64-nexora-none\nsection .text {\nfn h()->u32\neffects {}\nclobbers {} {\nreturn 1\n}\nfn g(in x:u32 @edi)->u32\neffects {}\nclobbers {} {\nreturn x\n}\nfn f()->u64\neffects {}\nclobbers {} {\ncall g(h())\nreturn 0\n}\n}\n";ok(&image,"nested call",nested,2,1,1);
const char*nested_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn h()->u32\neffects {}\nclobbers {} {\nreturn 1\n}\nfn g(in x:u64 @rdi)->u64\neffects {}\nclobbers {} {\nreturn x\n}\nfn f()->u64\neffects {}\nclobbers {} {\ncall g(h())\nreturn 0\n}\n}\n";err(&image,"nested mismatch",nested_bad,1,0);
const char*out_only="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(out x:u64 @rcx)->u64\neffects {}\nclobbers {} {\nreturn 0\n}\nfn f()->u64\neffects {}\nclobbers {} {\ncall g()\nreturn 0\n}\n}\n";ok(&image,"out",out_only,1,0,0);
const char*boolean="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in x:bool @al)->u64\neffects {}\nclobbers {} {\nreturn 0\n}\nfn f()->u64\neffects {}\nclobbers {} {\ncall g(true)\nreturn 0\n}\n}\n";ok(&image,"bool",boolean,1,1,1);
const char*expression="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in x:u64 @rdi)->u64\neffects {}\nclobbers {} {\nreturn x\n}\nfn f()->u64\neffects {changes_flags}\nclobbers {} {\ncall g(1+(2*3))\nreturn 0\n}\n}\n";ok(&image,"nested expression",expression,1,1,1);
const char*expression_mismatch="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in x:u64 @rdi)->u64\neffects {}\nclobbers {} {\nreturn x\n}\nfn f(in y:u32 @edi)->u64\neffects {changes_flags}\nclobbers {} {\ncall g(1+(y*3))\nreturn 0\n}\n}\n";err(&image,"nested mismatch",expression_mismatch,1,0);
const char*expression_range="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in x:u8 @al)->u8\neffects {}\nclobbers {} {\nreturn x\n}\nfn f()->u64\neffects {changes_flags}\nclobbers {} {\ncall g(1+(2*256))\nreturn 0\n}\n}\n";err(&image,"nested range",expression_range,2,0);
const char*expression_unknown="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in x:u64 @rdi)->u64\neffects {}\nclobbers {} {\nreturn x\n}\nfn f()->u64\neffects {changes_flags}\nclobbers {} {\ncall g(1+(-2))\nreturn 0\n}\n}\n";err(&image,"unsigned negative mismatch",expression_unknown,1,0);
const char*pointer="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in p:ptr<user,u8> @rdi)->u64\neffects {}\nclobbers {} {\nreturn 0\n}\nfn f(in q:ptr<user,u8> @rdi)->u64\neffects {}\nclobbers {} {\ncall g(q)\nreturn 0\n}\n}\n";ok(&image,"pointer",pointer,1,1,1);
const char*second_arg="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in a:u64 @rcx,in b:u64 @rdx)->u64\neffects {}\nclobbers {} {\nreturn a\n}\nfn f(in y:u32 @ecx)->u64\neffects {changes_flags}\nclobbers {} {\ncall g(1,1+(y*3))\nreturn 0\n}\n}\n";err(&image,"second argument mismatch",second_arg,1,1);
char deep[1024]="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in x:u64 @rdi)->u64\neffects {}\nclobbers {} {\nreturn x\n}\nfn f()->u64\neffects {}\nclobbers {} {\ncall g(";
for(unsigned i=0;i<65;i++)strcat(deep,"(");
strcat(deep,"1");
for(unsigned i=0;i<65;i++)strcat(deep,")");
strcat(deep,")\nreturn 0\n}\n}\n");
err(&image,"depth limit",deep,3,0);
const char*sibling="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in v:u64 @rcx)->u64\neffects {}\nclobbers {} {\nreturn v\n}\nfn f()->u64\neffects {}\nclobbers {} {\nif true {\nlet x:u64=1\n}\ncall g(x)\nreturn 0\n}\n}\n";err(&image,"sibling local not visible",sibling,3,0);
const char*simple_local="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in v:u64 @rcx)->u64\neffects {}\nclobbers {} {\nreturn v\n}\nfn f(in x:u64 @rcx)->u64\neffects {}\nclobbers {} {\ncall g(x)\nreturn 0\n}\n}\n";ok(&image,"simple argument name",simple_local,1,1,1);
const char*qualified_local="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in v:u64 @rcx)->u64\neffects {}\nclobbers {} {\nreturn v\n}\nfn f(in x:u64 @rcx)->u64\neffects {}\nclobbers {} {\ncall g(bogus.x)\nreturn 0\n}\n}\n";err(&image,"qualified argument rejected",qualified_local,3,0);
const char*unary_arguments="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in a:u64 @rcx,in b:u64 @rdx)->u64\neffects {}\nclobbers {} {\nreturn a\n}\nfn f(in x:u64 @rcx,in y:u64 @rdx)->u64\neffects {}\nclobbers {} {\ncall g(+x,~y)\nreturn 0\n}\n}\n";ok(&image,"unary plus and bitnot arguments",unary_arguments,1,2,2);
const char*negative_min="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in a:i8 @cl)->i8\neffects {}\nclobbers {} {\nreturn a\n}\nfn f()->u64\neffects {}\nclobbers {} {\ncall g(-128)\nreturn 0\n}\n}\n";ok(&image,"negative signed minimum argument",negative_min,1,1,1);
const char*negative_range="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in a:i8 @cl)->i8\neffects {}\nclobbers {} {\nreturn a\n}\nfn f()->u64\neffects {}\nclobbers {} {\ncall g(-129)\nreturn 0\n}\n}\n";err(&image,"negative signed range argument",negative_range,2,0);
const char*negative_unsigned="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in a:u8 @al)->u8\neffects {}\nclobbers {} {\nreturn a\n}\nfn f()->u64\neffects {}\nclobbers {} {\ncall g(-1)\nreturn 0\n}\n}\n";err(&image,"negative unsigned argument",negative_unsigned,1,0);
bad(&image,"short",literal,3);bad(&image,"invalid","target x86_64-nexora-none\n",4);
}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<11;i++)free(sources[i]);printf("NTASM_NOVA_CALL_TYPES checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
