#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include "x64.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static const uint8_t guard=0xcc;
static char*loadf(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime;uint8_t out[16];}Run;
static Run run(const NovaHostImage*i,uint64_t direction,uint64_t reg,uint64_t width,uint64_t base,uint64_t index,uint64_t scale,uint64_t disp,uint64_t segment,uint64_t features,uint64_t cpl,uint64_t words){Run r;memset(&r,0,sizeof r);memset(r.out,guard,sizeof r.out);NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t oh=nova_borrow_v2(&c,r.out,words,1);uint64_t a[]={direction,reg,width,base,index,scale,disp,segment,features,cpl,oh,words};r.returned=i->entry(&c,a,12);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void compare(const NovaHostImage*i,uint64_t direction,uint64_t reg,uint64_t width,uint64_t base,uint64_t index,uint64_t scale,uint64_t disp,uint64_t segment,uint64_t features,uint64_t cpl){int mapped_base=base==16?-1:base==17?-2:(int)base;int mapped_index=index==16?-1:(int)index;int64_t signed_disp=0;memcpy(&signed_disp,&disp,sizeof signed_disp);NtX64Operand gpr={.kind=NT_X64_REG,.width=(unsigned)width,.reg=(unsigned)reg};NtX64Operand mem={.kind=NT_X64_MEM,.width=(unsigned)width,.base=mapped_base,.index=mapped_index,.scale=(unsigned)scale,.disp=signed_disp,.segment=(NtX64Segment)segment};NtX64Operand operands[2];if(direction==0){operands[0]=gpr;operands[1]=mem;}else{operands[0]=mem;operands[1]=gpr;}NtX64Instruction expected={0};NtX64Context context={(uint32_t)features,(unsigned)cpl};NtX64Error e=nt_x64_encode("mov",operands,2,context,&expected);Run r=run(i,direction,reg,width,base,index,scale,disp,segment,features,cpl,16);cases++;checks++;int bad=r.returned!=(uint64_t)e||r.runtime;if(!e){bad|=r.out[0]!=expected.length;for(unsigned k=0;k<15;k++)bad|=r.out[k+1]!=(k<expected.length?expected.bytes[k]:0);}else for(unsigned k=0;k<16;k++)bad|=r.out[k]!=guard;if(bad){failures++;fprintf(stderr,"FAIL dir=%llu reg=%llu width=%llu base=%llu index=%llu scale=%llu disp=%llu seg=%llu ret=%llu oracle=%u\n",(unsigned long long)direction,(unsigned long long)reg,(unsigned long long)width,(unsigned long long)base,(unsigned long long)index,(unsigned long long)scale,(unsigned long long)disp,(unsigned long long)segment,(unsigned long long)r.returned,(unsigned)e);}}
typedef struct{uint64_t base,index,scale,disp,segment;}Desc;
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/x64-memory-entry.nova","toolchain/ntasm-nova/x64_fixed.nova"};char*sources[2]={0};NtFInput inputs[2];for(unsigned i=0;i<2;i++){size_t n=0;sources[i]=loadf(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=sources[0]&&sources[1];CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,2,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){const uint64_t widths[]={8,16,32,64};const uint64_t regs[]={0,4,8,15};const Desc descs[]={{0,16,1,0,0},{5,16,1,0,0},{4,16,1,0,0},{12,16,1,0,0},{8,16,1,127,0},{13,16,1,0,0},{0,1,2,128,0},{0,12,8,UINT64_MAX-127,0},{16,16,1,32,0},{16,2,4,UINT64_MAX-128,0},{17,16,1,2147483647,0},{0,16,1,1,1},{0,16,1,1,2}};for(unsigned d=0;d<2;d++)for(unsigned w=0;w<4;w++)for(unsigned r=0;r<4;r++)for(unsigned m=0;m<sizeof descs/sizeof *descs;m++)compare(&image,d,regs[r],widths[w],descs[m].base,descs[m].index,descs[m].scale,descs[m].disp,descs[m].segment,1,3);compare(&image,0,0,24,0,16,1,0,0,1,3);compare(&image,0,16,64,0,16,1,0,0,1,3);compare(&image,0,0,64,18,16,1,0,0,1,3);compare(&image,0,0,64,0,4,1,0,0,1,3);compare(&image,0,0,64,0,16,2,0,0,1,3);compare(&image,0,0,64,17,1,1,0,0,1,3);compare(&image,0,0,64,0,16,1,2147483648ULL,0,1,3);compare(&image,0,0,64,0,16,1,0,3,1,3);compare(&image,0,0,64,0,16,1,0,0,0,3);compare(&image,0,0,64,0,16,1,0,0,1,4);Run short_=run(&image,0,0,64,0,16,1,0,0,1,3,15);cases++;CHECK(short_.returned==800&&short_.runtime==0&&short_.out[0]==guard,"short output transactional");}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<2;i++)free(sources[i]);printf("NTASM_NOVA_X64_MEMORY checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
