#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;static const uint64_t guard=UINT64_C(0xcccccccccccccccc);
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static char*load(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime,out[4];}Run;
static Run run(const NovaHostImage*i,const char*s,uint64_t words){Run r={.out={guard,guard,guard,guard}};NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t sh=nova_borrow_v2(&c,(void*)s,strlen(s),0),oh=nova_borrow_v2(&c,r.out,words*8,1);uint64_t a[]={sh,strlen(s),oh,words};r.returned=i->entry(&c,a,4);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void ok(const NovaHostImage*i,const char*n,const char*s,uint64_t f,uint64_t m,uint64_t p){Run r=run(i,s,4);cases++;checks++;if(r.returned||r.runtime||r.out[0]!=f||r.out[1]!=m||r.out[2]!=p||r.out[3]){failures++;fprintf(stderr,"FAIL ok %s ret=%llu out=%llu,%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
static void err(const NovaHostImage*i,const char*n,const char*s,uint64_t words,uint64_t code,uint64_t reason,uint64_t index,int untouched){Run r=run(i,s,words);cases++;checks++;int bad=r.returned!=code||r.runtime;if(untouched)bad|=r.out[0]!=guard||r.out[1]!=guard;else bad|=r.out[0]==guard||r.out[1]==guard||r.out[2]!=reason||r.out[3]!=index;if(bad){failures++;fprintf(stderr,"FAIL error %s ret=%llu out=%llu,%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/abi-entry.nova","toolchain/ntasm-nova/abi.nova","toolchain/ntasm-nova/clobbers.nova","toolchain/ntasm-nova/register_widths.nova","toolchain/ntasm-nova/register_bindings.nova","toolchain/ntasm-nova/parameters.nova","toolchain/ntasm-nova/callable_names.nova","toolchain/ntasm-nova/semantics.nova","toolchain/ntasm-nova/parser.nova","toolchain/ntasm-nova/ast.nova","toolchain/ntasm-nova/lexer.nova"};char*sources[11]={0};NtFInput inputs[11];for(unsigned i=0;i<11;i++){size_t n=0;sources[i]=load(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=1;for(unsigned i=0;i<11;i++)if(!sources[i])all=0;CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,11,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){
const char*implicit="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in a:u64,in b:u64,in c:u64,in d:u64)->u64\neffects {}\nclobbers {} {\nreturn a\n}\n}\n";ok(&image,"implicit",implicit,1,0,4);
const char*explicit_="module m\ntarget x86_64-nexora-none\ndefault_abi nx64-abi-v0\nsection .text {\nfn f()->u64\nabi nx64-abi-v0\neffects {}\nclobbers {} {\nreturn 0\n}\n}\n";ok(&image,"explicit",explicit_,1,0,0);
const char*bad_default="module m\ntarget x86_64-nexora-none\ndefault_abi alien-abi\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nreturn 0\n}\n}\n";err(&image,"default",bad_default,4,327,1,0,0);
const char*bad_explicit="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\nabi alien-abi\neffects {}\nclobbers {} {\nreturn 0\n}\n}\n";err(&image,"explicit bad",bad_explicit,4,327,2,0,0);
const char*fifteen="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in a:u64 @rcx,in b:u64 @rdx,in c:u64 @r8,in d:u64 @r9,in e:u64 @rax,in f:u64 @rbx,in g:u64 @rsi,in h:u64 @rdi,in i:u64 @r10,in j:u64 @r11,in k:u64 @r12,in l:u64 @r13,in m:u64 @r14,in n:u64 @r15,in o:u64 @rbp)->u64\neffects {}\nclobbers {} {\nreturn a\n}\n}\n";err(&image,"fifteen",fifteen,4,328,1,14,0);
const char*fifth="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in a:u64,in b:u64,in c:u64,in d:u64,in e:u64)->u64\neffects {}\nclobbers {} {\nreturn a\n}\n}\n";err(&image,"fifth",fifth,4,328,2,4,0);
const char*out_unbound="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(out a:u64)->u64\neffects {}\nclobbers {} {\nreturn 0\n}\n}\n";err(&image,"out",out_unbound,4,328,3,0,0);
const char*inout_unbound="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(inout a:u64)->u64\neffects {}\nclobbers {} {\nreturn a\n}\n}\n";err(&image,"inout",inout_unbound,4,328,3,0,0);
const char*out_bool="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(out a:bool @al)->u64\neffects {}\nclobbers {} {\nreturn 0\n}\n}\n";err(&image,"bool",out_bool,4,329,1,0,0);
const char*pointer_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<user,u64> @edi)->u64\neffects {}\nclobbers {} {\nreturn 0\n}\n}\n";err(&image,"ptr32",pointer_bad,4,329,2,0,0);
const char*pointer_ok="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<user,u64> @rdi)->u64\neffects {}\nclobbers {} {\nreturn 0\n}\n}\n";ok(&image,"ptr64",pointer_ok,1,0,1);
const char*unknown_reg="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in a:u64 @foo)->u64\neffects {}\nclobbers {} {\nreturn a\n}\n}\n";err(&image,"reg",unknown_reg,4,328,4,0,0);
const char*imported="module m\ntarget x86_64-nexora-none\nimport a.f as f: fn(in p:ptr<user,u64> @rdi)->u64\nabi nx64-abi-v0\neffects {}\nclobbers {}\n";ok(&image,"import",imported,0,1,1);
const char*out_ok="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(out a:u64 @rcx)->u64\neffects {}\nclobbers {} {\nreturn a\n}\n}\n";ok(&image,"out ok",out_ok,1,0,1);const char*out_reserved="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(out a:u64 @rax)->u64\neffects {}\nclobbers {} {\nreturn a\n}\n}\n";err(&image,"out reserved",out_reserved,4,328,5,0,0);const char*out_overlap="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(out a:u64 @rcx)->u64\neffects {}\nclobbers {ecx} {\nreturn a\n}\n}\n";err(&image,"out clobber",out_overlap,4,328,6,0,0);err(&image,"short",implicit,3,800,0,0,1);err(&image,"invalid","target x86_64-nexora-none\n",4,800,0,0,1);
}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<11;i++)free(sources[i]);printf("NTASM_NOVA_ABI checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
