#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;static const uint64_t guard=UINT64_C(0xcccccccccccccccc);
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static char*load(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime,out[4];}Run;
static Run run(const NovaHostImage*i,const char*s,uint64_t words){Run r={.out={guard,guard,guard,guard}};NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t sh=nova_borrow_v2(&c,(void*)s,strlen(s),0),oh=nova_borrow_v2(&c,r.out,words*8,1);uint64_t a[]={sh,strlen(s),oh,words};r.returned=i->entry(&c,a,4);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void ok(const NovaHostImage*i,const char*n,const char*s,uint64_t d,uint64_t c,uint64_t p){Run r=run(i,s,4);cases++;checks++;if(r.returned||r.runtime||r.out[0]!=d||r.out[1]!=c||r.out[2]!=p||r.out[3]){failures++;fprintf(stderr,"FAIL ok %s ret=%llu out=%llu,%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
static void err(const NovaHostImage*i,const char*n,const char*s,uint64_t words,uint64_t family,uint64_t index,int untouched){Run r=run(i,s,words);cases++;checks++;int bad=r.returned!=326||r.runtime;if(untouched)bad|=r.out[0]!=guard||r.out[1]!=guard;else bad|=r.out[0]==guard||r.out[1]==guard||r.out[2]!=family||r.out[3]!=index;if(bad){failures++;fprintf(stderr,"FAIL error %s ret=%llu out=%llu,%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
static void badinput(const NovaHostImage*i,const char*n,const char*s,uint64_t words){Run r=run(i,s,words);cases++;checks++;if(r.returned!=800||r.runtime||r.out[0]!=guard||r.out[1]!=guard){failures++;fprintf(stderr,"FAIL invalid %s ret=%llu\n",n,(unsigned long long)r.returned);}}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/call-contracts-entry.nova","toolchain/ntasm-nova/call_contracts.nova","toolchain/ntasm-nova/call_effects.nova","toolchain/ntasm-nova/calls.nova","toolchain/ntasm-nova/refs.nova","toolchain/ntasm-nova/contracts.nova","toolchain/ntasm-nova/feature_requirements.nova","toolchain/ntasm-nova/features.nova","toolchain/ntasm-nova/effects.nova","toolchain/ntasm-nova/callable_names.nova","toolchain/ntasm-nova/semantics.nova","toolchain/ntasm-nova/parser.nova","toolchain/ntasm-nova/ast.nova","toolchain/ntasm-nova/lexer.nova"};char*sources[14]={0};NtFInput inputs[14];for(unsigned i=0;i<14;i++){size_t n=0;sources[i]=load(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=1;for(unsigned i=0;i<14;i++)if(!sources[i])all=0;CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,14,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){
const char*none="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {}\nclobbers {} {\nreturn 0\n}\nfn main()->u64\neffects {}\nclobbers {} {\ncall leaf()\nreturn 0\n}\n}\n";ok(&image,"none",none,2,1,0);
const char*feature_ok="module m\ntarget x86_64-nexora-none\nfeatures {sse2}\nsection .text {\nfn leaf()->u64\neffects {}\nclobbers {}\nrequires {feature(sse2)} {\nreturn 0\n}\nfn main()->u64\neffects {}\nclobbers {}\nrequires {feature(sse2)} {\ncall leaf()\nreturn 0\n}\n}\n";ok(&image,"feature",feature_ok,2,1,1);
const char*feature_bad="module m\ntarget x86_64-nexora-none\nfeatures {sse2}\nsection .text {\nfn leaf()->u64\neffects {}\nclobbers {}\nrequires {feature(sse2)} {\nreturn 0\n}\nfn main()->u64\neffects {}\nclobbers {} {\ncall leaf()\nreturn 0\n}\n}\n";ok(&image,"feature module proof",feature_bad,2,1,1);
const char*stack_ok="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {}\nclobbers {}\nrequires {stack_aligned(16)} {\nreturn 0\n}\nfn main()->u64\neffects {}\nclobbers {}\nrequires {stack_aligned(16)} {\ncall leaf()\nreturn 0\n}\n}\n";ok(&image,"stack",stack_ok,2,1,1);
const char*stack_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {}\nclobbers {}\nrequires {stack_aligned(16)} {\nreturn 0\n}\nfn main()->u64\neffects {}\nclobbers {}\nrequires {stack_aligned(8)} {\ncall leaf()\nreturn 0\n}\n}\n";ok(&image,"stack abi baseline",stack_bad,2,1,1);
const char*stack_too_large="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {}\nclobbers {}\nrequires {stack_aligned(32)} {\nreturn 0\n}\nfn main()->u64\neffects {}\nclobbers {} {\ncall leaf()\nreturn 0\n}\n}\n";err(&image,"stack too large",stack_too_large,4,4,0,0);
const char*nonnull_ok="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf(in p:ptr<user,u64> @rdi)->u64\neffects {}\nclobbers {}\nrequires {non_null(p)} {\nreturn 0\n}\nfn main(in q:ptr<user,u64> @rdi)->u64\neffects {}\nclobbers {}\nrequires {non_null(q)} {\ncall leaf(q)\nreturn 0\n}\n}\n";ok(&image,"nonnull mapped",nonnull_ok,2,1,1);
const char*nonnull_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf(in p:ptr<user,u64> @rdi)->u64\neffects {}\nclobbers {}\nrequires {non_null(p)} {\nreturn 0\n}\nfn main(in q:ptr<user,u64> @rdi)->u64\neffects {}\nclobbers {} {\ncall leaf(q)\nreturn 0\n}\n}\n";err(&image,"nonnull missing",nonnull_bad,4,2,0,0);
const char*canonical_ok="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf(in p:ptr<user,u64> @rdi)->u64\neffects {}\nclobbers {}\nrequires {canonical(p)} {\nreturn 0\n}\nfn main(in q:ptr<user,u64> @rdi)->u64\neffects {}\nclobbers {}\nrequires {canonical(q)} {\ncall leaf(q)\nreturn 0\n}\n}\n";ok(&image,"canonical",canonical_ok,2,1,1);
const char*literal_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf(in p:ptr<user,u64> @rdi)->u64\neffects {}\nclobbers {}\nrequires {non_null(p)} {\nreturn 0\n}\nfn main()->u64\neffects {}\nclobbers {} {\ncall leaf(1)\nreturn 0\n}\n}\n";err(&image,"literal not proved",literal_bad,4,2,0,0);
const char*unsupported="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {}\nclobbers {}\nrequires {stack_in(kernel)} {\nreturn 0\n}\nfn main()->u64\neffects {}\nclobbers {}\nrequires {stack_in(kernel)} {\ncall leaf()\nreturn 0\n}\n}\n";err(&image,"unsupported",unsupported,4,5,0,0);
const char*unsupported_zero="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {}\nclobbers {}\nrequires {interrupts_enabled()} {\nreturn 0\n}\nfn main()->u64\neffects {}\nclobbers {}\nrequires {interrupts_enabled()} {\ncall leaf()\nreturn 0\n}\n}\n";err(&image,"unsupported zero",unsupported_zero,4,5,0,0);
const char*imported="module m\ntarget x86_64-nexora-none\nfeatures {sse2}\nimport a.f as f: fn()->u64\neffects {}\nclobbers {}\nrequires {feature(sse2)}\nsection .text {\nfn main()->u64\neffects {}\nclobbers {}\nrequires {feature(sse2)} {\nreturn f()\n}\n}\n";ok(&image,"import expression",imported,2,1,1);
badinput(&image,"short",none,3);badinput(&image,"invalid","target x86_64-nexora-none\n",4);
}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<14;i++)free(sources[i]);printf("NTASM_NOVA_CALL_CONTRACTS checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
