#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include "x64.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static const uint8_t guard=0xcc;
static char*loadf(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime;uint8_t out[16];}Run;
static Run run(const NovaHostImage*i,const char*name,uint64_t count,uint64_t destination,uint64_t width,uint64_t amount,uint64_t features,uint64_t cpl,uint64_t mode,uint64_t words){Run r;memset(&r,0,sizeof r);memset(r.out,guard,sizeof r.out);NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t nh=nova_borrow_v2(&c,(void*)name,strlen(name),0),oh=nova_borrow_v2(&c,r.out,words,1);uint64_t a[]={nh,strlen(name),count,destination,width,amount,features,cpl,mode,oh,words};r.returned=i->entry(&c,a,11);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void compare(const NovaHostImage*i,const char*name,uint64_t count,uint64_t destination,uint64_t width,uint64_t amount,uint64_t features,uint64_t cpl,uint64_t mode){NtX64Operand operands[2]={{.kind=NT_X64_REG,.width=(unsigned)width,.reg=(unsigned)destination},{.kind=NT_X64_IMM,.imm=amount}};NtX64Instruction expected={0};NtX64Context context={(uint32_t)features,(unsigned)cpl};NtX64Error e=nt_x64_encode(name,operands,(size_t)count,context,&expected);Run r=run(i,name,count,destination,width,amount,features,cpl,mode,16);cases++;checks++;int bad=r.returned!=(uint64_t)e||r.runtime;if(!e){bad|=r.out[0]!=expected.length;unsigned capacity=mode?5:4;for(unsigned k=0;k<15;k++){uint8_t want=k<expected.length?expected.bytes[k]:(k<capacity?0:guard);bad|=r.out[k+1]!=want;}}else for(unsigned k=0;k<16;k++)bad|=r.out[k]!=guard;if(bad){failures++;fprintf(stderr,"FAIL %s mode=%llu count=%llu reg=%llu width=%llu amount=%llu ret=%llu oracle=%u\n",name,(unsigned long long)mode,(unsigned long long)count,(unsigned long long)destination,(unsigned long long)width,(unsigned long long)amount,(unsigned long long)r.returned,(unsigned)e);}}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/x64-unary-shift-entry.nova","toolchain/ntasm-nova/x64_fixed.nova"};char*sources[2]={0};NtFInput inputs[2];for(unsigned i=0;i<2;i++){size_t n=0;sources[i]=loadf(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=sources[0]&&sources[1];CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,2,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){const char*unary[]={"inc","dec","not","neg"};const char*shifts[]={"rol","ror","shl","shr","sar"};const uint64_t widths[]={8,16,32,64};const uint64_t regs[]={0,4,8,15};const uint64_t amounts[]={0,1,2,255,256};for(unsigned n=0;n<4;n++)for(unsigned w=0;w<4;w++)for(unsigned r=0;r<4;r++)compare(&image,unary[n],1,regs[r],widths[w],0,1,3,0);for(unsigned n=0;n<5;n++)for(unsigned w=0;w<4;w++)for(unsigned r=0;r<4;r++)for(unsigned m=0;m<5;m++)compare(&image,shifts[n],2,regs[r],widths[w],amounts[m],1,3,1);compare(&image,"telepathy",1,0,64,0,1,3,0);compare(&image,"inc",2,0,64,0,1,3,0);compare(&image,"inc",1,16,64,0,1,3,0);compare(&image,"inc",1,0,24,0,1,3,0);compare(&image,"inc",1,0,64,0,0,3,0);compare(&image,"inc",1,0,64,0,1,4,0);Run short_=run(&image,"shl",2,0,64,1,1,3,1,5);cases++;CHECK(short_.returned==800&&short_.runtime==0&&short_.out[0]==guard,"short output transactional");}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<2;i++)free(sources[i]);printf("NTASM_NOVA_X64_UNARY_SHIFT checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
