#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static const uint64_t guard=UINT64_C(0xcccccccccccccccc);
static char*load(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime,out[4];}Run;
static Run run(const NovaHostImage*i,const char*s,uint64_t words){Run r={.out={guard,guard,guard,guard}};NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t sh=nova_borrow_v2(&c,(void*)s,strlen(s),0),oh=nova_borrow_v2(&c,r.out,words*8,1);uint64_t a[]={sh,strlen(s),oh,words};r.returned=i->entry(&c,a,4);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void expect(const NovaHostImage*i,const char*n,const char*s,uint64_t words,uint64_t code,int untouched){Run r=run(i,s,words);cases++;checks++;if(r.returned!=code||r.runtime||(code==0&&(r.out[0]!=33||r.out[1]==0||r.out[2]==0||r.out[3]!=0))||(untouched&&(r.out[0]!=guard||r.out[1]!=guard))){failures++;fprintf(stderr,"FAIL %s ret=%llu runtime=%llu out=%llu,%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.runtime,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/validate-entry.nova","toolchain/ntasm-nova/validate.nova","toolchain/ntasm-nova/constant_types.nova","toolchain/ntasm-nova/initializer_types.nova","toolchain/ntasm-nova/condition_types.nova","toolchain/ntasm-nova/literal_initializers.nova","toolchain/ntasm-nova/targets.nova","toolchain/ntasm-nova/versions.nova","toolchain/ntasm-nova/feature_requirements.nova","toolchain/ntasm-nova/features.nova","toolchain/ntasm-nova/pointer_spaces.nova","toolchain/ntasm-nova/control_flow.nova","toolchain/ntasm-nova/return_types.nova","toolchain/ntasm-nova/body_clobbers.nova","toolchain/ntasm-nova/body_intrinsics.nova","toolchain/ntasm-nova/body_effects.nova","toolchain/ntasm-nova/call_contracts.nova","toolchain/ntasm-nova/abi.nova","toolchain/ntasm-nova/call_clobbers.nova","toolchain/ntasm-nova/call_effects.nova","toolchain/ntasm-nova/call_types.nova","toolchain/ntasm-nova/calls.nova","toolchain/ntasm-nova/refs.nova","toolchain/ntasm-nova/clobbers.nova","toolchain/ntasm-nova/contracts.nova","toolchain/ntasm-nova/effects.nova","toolchain/ntasm-nova/register_widths.nova","toolchain/ntasm-nova/register_bindings.nova","toolchain/ntasm-nova/bindings.nova","toolchain/ntasm-nova/locals.nova","toolchain/ntasm-nova/parameters.nova","toolchain/ntasm-nova/types.nova","toolchain/ntasm-nova/symbol_names.nova","toolchain/ntasm-nova/callable_names.nova","toolchain/ntasm-nova/semantics.nova","toolchain/ntasm-nova/parser.nova","toolchain/ntasm-nova/ast.nova","toolchain/ntasm-nova/lexer.nova"};char*sources[38]={0};NtFInput inputs[38];for(unsigned i=0;i<38;i++){size_t n=0;sources[i]=load(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=1;for(unsigned i=0;i<38;i++)if(!sources[i])all=0;CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,38,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");
 if(image.memory){
  const char*valid="module m\ntarget x86_64-nexora-none\nsection .rdata {\ndata answer:u64=42\n}\nsection .text {\nfn helper(in x:u64 @rcx)->u64\neffects {}\nclobbers {rax} {\nlet y:u64=x\nreturn y\n}\nfn main()->u64\neffects {}\nclobbers {rax} {\ncall helper(1)\nreturn 0\n}\n}\n";expect(&image,"valid",valid,4,0,0);
  const char*dupfn="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nreturn 0\n}\nfn f()->u64\neffects {}\nclobbers {} {\nreturn 1\n}\n}\n";expect(&image,"300",dupfn,4,300,0);
  const char*aliases="module m\ntarget x86_64-nexora-none\nimport a.f as x: fn()->u64\neffects {}\nclobbers {}\nimport b.f as x: fn()->u64\neffects {}\nclobbers {}\n";expect(&image,"313",aliases,4,313,0);
  const char*symbols="module m\ntarget x86_64-nexora-none\nsection .rdata {\ndata same:u64=1\n}\nsection .text {\nfn same()->u64\neffects {}\nclobbers {} {\nreturn 0\n}\n}\n";expect(&image,"319",symbols,4,319,0);
  const char*params="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rcx,in x:u64 @rdx)->u64\neffects {}\nclobbers {} {\nreturn x\n}\n}\n";expect(&image,"314",params,4,314,0);
  const char*locals="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nlet x:u64=1\nlet x:u64=2\nreturn x\n}\n}\n";expect(&image,"315",locals,4,315,0);
  const char*bindings="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rcx)->u64\neffects {}\nclobbers {} {\nlet x:u64=1\nreturn x\n}\n}\n";expect(&image,"316",bindings,4,316,0);
  const char*registers="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in a:u64 @rcx,in b:u64 @rcx)->u64\neffects {}\nclobbers {} {\nreturn a\n}\n}\n";expect(&image,"317",registers,4,317,0);
  const char*width="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @ecx)->u64\neffects {}\nclobbers {} {\nreturn x\n}\n}\n";expect(&image,"318",width,4,318,0);
  const char*clobber="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {rax,rax} {\nreturn 0\n}\n}\n";expect(&image,"320",clobber,4,320,0);
  const char*missing="module m\ntarget x86_64-nexora-none\nsection .text {\nfn main()->u64\neffects {}\nclobbers {} {\ncall absent()\nreturn 0\n}\n}\n";expect(&image,"310",missing,4,310,0);
  const char*arity="module m\ntarget x86_64-nexora-none\nsection .text {\nfn helper(in x:u64 @rcx)->u64\neffects {}\nclobbers {} {\nreturn x\n}\nfn main()->u64\neffects {}\nclobbers {} {\ncall helper()\nreturn 0\n}\n}\n";expect(&image,"311",arity,4,311,0);
  const char*param_alias="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in a:u64 @rcx,in b:u32 @ecx)->u64\neffects {}\nclobbers {} {\nreturn a\n}\n}\n";expect(&image,"317 alias",param_alias,4,317,0);
  const char*clobber_alias="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {r10,r10d} {\nreturn 0\n}\n}\n";expect(&image,"320 alias",clobber_alias,4,320,0);
  const char*unknown_effect="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {telepathy}\nclobbers {} {\nreturn 0\n}\n}\n";expect(&image,"321 effect",unknown_effect,4,321,0);
  const char*duplicate_effect="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {msr,msr}\nclobbers {} {\nreturn 0\n}\n}\n";expect(&image,"322 effect",duplicate_effect,4,322,0);
  const char*unknown_contract="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {}\nrequires {telepathy(1)} {\nreturn 0\n}\n}\n";expect(&image,"323 contract",unknown_contract,4,323,0);
  const char*contract_arity="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {}\nrequires {valid_user_return(1)} {\nreturn 0\n}\n}\n";expect(&image,"324 contract",contract_arity,4,324,0);
  const char*missing_effect="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {privileged}\nclobbers {} {\nreturn 0\n}\nfn main()->u64\neffects {}\nclobbers {} {\ncall leaf()\nreturn 0\n}\n}\n";expect(&image,"325 call effect",missing_effect,4,325,0);
  const char*missing_nonnull_contract="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf(in p:ptr<user,u64> @rdi)->u64\neffects {}\nclobbers {}\nrequires {non_null(p)} {\nreturn 0\n}\nfn main(in q:ptr<user,u64> @rdi)->u64\neffects {}\nclobbers {} {\ncall leaf(q)\nreturn 0\n}\n}\n";expect(&image,"326 nonnull contract",missing_nonnull_contract,4,326,0);
  const char*bad_abi="module m\ntarget x86_64-nexora-none\ndefault_abi alien-abi\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nreturn 0\n}\n}\n";expect(&image,"327 abi",bad_abi,4,327,0);
  const char*fifth_param="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in a:u64,in b:u64,in c:u64,in d:u64,in e:u64)->u64\neffects {}\nclobbers {} {\nreturn a\n}\n}\n";expect(&image,"328 abi",fifth_param,4,328,0);
  const char*pointer_width="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<user,u64> @edi)->u64\neffects {}\nclobbers {} {\nreturn 0\n}\n}\n";expect(&image,"329 abi",pointer_width,4,329,0);
  const char*missing_contract="module m\ntarget x86_64-nexora-none\nfeatures {sse2}\nsection .text {\nfn leaf()->u64\neffects {}\nclobbers {}\nrequires {feature(sse2)} {\nreturn 0\n}\nfn main()->u64\neffects {}\nclobbers {} {\ncall leaf()\nreturn 0\n}\n}\n";expect(&image,"feature module call proof",missing_contract,4,0,0);
  const char*unknown_clobber="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {foo} {\nreturn 0\n}\n}\n";expect(&image,"330 clobber",unknown_clobber,4,330,0);
  const char*missing_clobber="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {}\nclobbers {rax} {\nreturn 0\n}\nfn main()->u64\neffects {}\nclobbers {} {\ncall leaf()\nreturn 0\n}\n}\n";expect(&image,"331 call clobber",missing_clobber,4,331,0);
  const char*missing_body_effect="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<user,u64> @rdi)->u64\neffects {}\nclobbers {rax} {\nload rax,[p]:ptr<user,u64>\nreturn rax\n}\n}\n";expect(&image,"332 body effect",missing_body_effect,4,332,0);
  const char*unknown_space="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<alien,u64> @rdi)->u64\neffects {reads_mem}\nclobbers {rax} {\nload rax,[p]:ptr<alien,u64>\nreturn rax\n}\n}\n";expect(&image,"340 load pointer space",unknown_space,4,340,0);
  const char*missing_intrinsic="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {rax,rdx} {\nrdtsc\nreturn 0\n}\n}\n";expect(&image,"334 intrinsic",missing_intrinsic,4,334,0);
  const char*missing_load_clobber="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<user,u64> @rdi)->u64\neffects {reads_mem(user)}\nclobbers {} {\nload rax,[p]:ptr<user,u64>\nreturn rax\n}\n}\n";expect(&image,"335 body clobber",missing_load_clobber,4,335,0);
  const char*unknown_load_register="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<user,u64> @rdi)->u64\neffects {reads_mem(user)}\nclobbers {} {\nload foo,[p]:ptr<user,u64>\nreturn 0\n}\n}\n";expect(&image,"336 body register",unknown_load_register,4,336,0);
  const char*never_return="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->never\neffects {no_return}\nclobbers {} {\nreturn 0\n}\n}\n";expect(&image,"337 never return",never_return,4,337,0);
  const char*fallthrough="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nnop\n}\n}\n";expect(&image,"338 fallthrough",fallthrough,4,338,0);
  const char*bare_return="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nreturn\n}\n}\n";expect(&image,"339 bare return",bare_return,4,339,0);
  const char*never_call_ok="module m\ntarget x86_64-nexora-none\nsection .text {\nfn halt()->never\neffects {no_return}\nclobbers {} {\nud2\n}\nfn main()->never\neffects {no_return}\nclobbers {} {\ncall halt()\n}\n}\n";expect(&image,"never call terminal",never_call_ok,4,0,0);
  const char*bad_pointer_space="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<alien,u64> @rdi)->u64\neffects {}\nclobbers {} {\nreturn 0\n}\n}\n";expect(&image,"340 pointer space",bad_pointer_space,4,340,0);
  const char*missing_intrinsic_clobber="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {control,changes_flags}\nclobbers {rcx} {\nsyscall\nreturn 0\n}\n}\n";expect(&image,"335 intrinsic clobber",missing_intrinsic_clobber,4,335,0);
  const char*missing_mov_clobber="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rbx)->u64\neffects {}\nclobbers {} {\nmov rax,rbx\nreturn rax\n}\n}\n";expect(&image,"335 mov clobber",missing_mov_clobber,4,335,0);
  const char*missing_xchg_clobber="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rax,in y:u64 @rcx)->u64\neffects {}\nclobbers {rax} {\nxchg rax,rcx\nreturn rax\n}\n}\n";expect(&image,"335 xchg clobber",missing_xchg_clobber,4,335,0);
  const char*missing_arith_flags="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rax)->u64\neffects {}\nclobbers {r10} {\nadd r10,rax\nreturn r10\n}\n}\n";expect(&image,"334 arithmetic flags",missing_arith_flags,4,334,0);
  const char*unknown_feature="module m\ntarget x86_64-nexora-none\nfeatures {avx512}\n";expect(&image,"341 feature",unknown_feature,4,341,0);
  const char*duplicate_feature="module m\ntarget x86_64-nexora-none\nfeatures {sse2,sse2}\n";expect(&image,"342 feature",duplicate_feature,4,342,0);
  const char*unknown_required_feature="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {}\nrequires {feature(avx512)} {\nreturn 0\n}\n}\n";expect(&image,"343 required feature",unknown_required_feature,4,343,0);
  const char*unavailable_feature="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {}\nrequires {feature(sse2)} {\nreturn 0\n}\n}\n";expect(&image,"344 unavailable feature",unavailable_feature,4,344,0);
  const char*unknown_target="module m\ntarget x86_64-other-none\n";expect(&image,"345 target",unknown_target,4,345,0);
  const char*wrong_version="module m\ntarget x86_64-nexora-none\nversions {\nntir 1.0\nmachine_ir 0.1\nsections 0.1\nsymbols 0.1\nrelocations 0.1\nnxo 0.1\n}\n";expect(&image,"348 version",wrong_version,4,348,0);
  const char*incomplete_versions="module m\ntarget x86_64-nexora-none\nversions {\nntir 0.1\n}\n";expect(&image,"349 versions",incomplete_versions,4,349,0);
  const char*out_reserved="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(out a:u64 @rax)->u64\neffects {}\nclobbers {} {\nreturn a\n}\n}\n";expect(&image,"328 reserved output",out_reserved,4,328,0);
  const char*out_clobber="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(out a:u64 @rcx)->u64\neffects {}\nclobbers {ecx} {\nreturn a\n}\n}\n";expect(&image,"328 output clobber",out_clobber,4,328,0);
  const char*unknown_type="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:telepathy @rdi)->u64\neffects {}\nclobbers {} {\nreturn 0\n}\n}\n";expect(&image,"350 type",unknown_type,4,350,0);
  const char*zero_array="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:array<u8,0> @rdi)->u64\neffects {}\nclobbers {} {\nreturn 0\n}\n}\n";expect(&image,"351 array",zero_array,4,351,0);
  const char*return_mismatch="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u32 @edi)->u64\neffects {}\nclobbers {} {\nreturn x\n}\n}\n";expect(&image,"352 return type",return_mismatch,4,352,0);
  const char*return_range="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u8\neffects {}\nclobbers {} {\nreturn 256\n}\n}\n";expect(&image,"353 return range",return_range,4,353,0);
  const char*out_call_ok="module m\ntarget x86_64-nexora-none\nsection .text {\nfn helper(out x:u64 @rcx)->u64\neffects {}\nclobbers {} {\nreturn 0\n}\nfn main()->u64\neffects {}\nclobbers {} {\ncall helper()\nreturn 0\n}\n}\n";expect(&image,"out call arity",out_call_ok,4,0,0);
  const char*inout_call_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn helper(inout x:u64 @rcx)->u64\neffects {}\nclobbers {} {\nreturn x\n}\nfn main()->u64\neffects {}\nclobbers {} {\ncall helper()\nreturn 0\n}\n}\n";expect(&image,"inout call arity",inout_call_bad,4,311,0);
  const char*call_type_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in x:u64 @rdi)->u64\neffects {}\nclobbers {} {\nreturn x\n}\nfn f(in y:u32 @edi)->u64\neffects {}\nclobbers {} {\ncall g(y)\nreturn 0\n}\n}\n";expect(&image,"354 call type",call_type_bad,4,354,0);
  const char*call_range_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn g(in x:u8 @al)->u8\neffects {}\nclobbers {} {\nreturn x\n}\nfn f()->u64\neffects {}\nclobbers {} {\ncall g(256)\nreturn 0\n}\n}\n";expect(&image,"354 call range",call_range_bad,4,354,0);
  const char*initializer_type_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nlet x:bool=1\nreturn 0\n}\n}\n";expect(&image,"355 initializer type",initializer_type_bad,4,355,0);
  const char*initializer_range_bad="module m\ntarget x86_64-nexora-none\nsection .rdata {\ndata x:u8=256\n}\n";expect(&image,"356 initializer range",initializer_range_bad,4,356,0);
  const char*condition_type_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nif 1 {\nreturn 1\n} else {\nreturn 0\n}\n}\n}\n";expect(&image,"357 condition type",condition_type_bad,4,357,0);
  const char*condition_shape_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rcx)->u64\neffects {changes_flags}\nclobbers {} {\nif x+1 {\nreturn 1\n} else {\nreturn 0\n}\n}\n}\n";expect(&image,"358 condition shape",condition_shape_bad,4,358,0);
  const char*bool_condition_call="module m\ntarget x86_64-nexora-none\nsection .text {\nfn pred()->bool\neffects {}\nclobbers {} {\nreturn true\n}\nfn f()->u64\neffects {}\nclobbers {} {\nif pred() {\nreturn 1\n} else {\nreturn 0\n}\n}\n}\n";expect(&image,"bool condition call",bool_condition_call,4,0,0);
  const char*missing_condition_call="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nif absent() {\nreturn 1\n} else {\nreturn 0\n}\n}\n}\n";expect(&image,"missing condition call",missing_condition_call,4,310,0);
  const char*initializer_name_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:u32 @ecx)->u64\neffects {}\nclobbers {} {\nlet x:u64=p\nreturn x\n}\n}\n";expect(&image,"359 initializer name",initializer_name_bad,4,359,0);
  const char*initializer_arithmetic="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:u64 @rcx)->u64\neffects {changes_flags}\nclobbers {} {\nlet x:u64=p+1\nreturn x\n}\n}\n";expect(&image,"initializer arithmetic",initializer_arithmetic,4,0,0);
  const char*initializer_arithmetic_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:u32 @ecx)->u64\neffects {changes_flags}\nclobbers {} {\nlet x:u64=p+1\nreturn x\n}\n}\n";expect(&image,"359 initializer arithmetic",initializer_arithmetic_bad,4,359,0);
  const char*initializer_shape_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:u64 @rcx)->u64\neffects {changes_flags}\nclobbers {} {\nlet x:u64=p+(1+2)\nreturn x\n}\n}\n";expect(&image,"360 initializer shape",initializer_shape_bad,4,360,0);
  const char*constant_type_bad="module m\ntarget x86_64-nexora-none\nconst ready:bool=1\n";expect(&image,"361 constant type",constant_type_bad,4,361,0);
  const char*constant_range_bad="module m\ntarget x86_64-nexora-none\nconst byte:u8=256\n";expect(&image,"362 constant range",constant_range_bad,4,362,0);
  const char*constant_shape_bad="module m\ntarget x86_64-nexora-none\nconst sum:u64=1+2\n";expect(&image,"363 constant shape",constant_shape_bad,4,363,0);
  expect(&image,"short",valid,3,800,1);expect(&image,"invalid","target x86_64-nexora-none\n",4,800,1);
 }
 if(image.memory) nova_host_unmap(&image);
 if(compiled) nt_artifact_free(&a);
 for(unsigned i=0;i<38;i++) free(sources[i]);
 printf("NTASM_NOVA_VALIDATE checks=%u failures=%u cases=%u\n",checks,failures,cases);
 return failures?1:0;
}
