#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include "x64.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;static const uint8_t guard=0xcc;
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static char*loadf(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime;uint8_t out[5];}Run;static Run run(const NovaHostImage*i,const char*name,uint64_t count,uint64_t reg,uint64_t width,uint64_t features,uint64_t cpl,uint64_t words){Run r;memset(&r,0,sizeof r);memset(r.out,guard,sizeof r.out);NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t nh=nova_borrow_v2(&c,(void*)name,strlen(name),0),oh=nova_borrow_v2(&c,r.out,words,1);uint64_t a[]={nh,strlen(name),count,reg,width,features,cpl,oh,words};r.returned=i->entry(&c,a,9);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void compare(const NovaHostImage*i,const char*name,uint64_t count,uint64_t reg,uint64_t width,uint64_t features,uint64_t cpl){NtX64Operand operand={.kind=NT_X64_REG,.width=(unsigned)width,.reg=(unsigned)reg};NtX64Instruction expected={0};NtX64Context context={(uint32_t)features,(unsigned)cpl};NtX64Error e=nt_x64_encode(name,&operand,(size_t)count,context,&expected);Run r=run(i,name,count,reg,width,features,cpl,5);cases++;checks++;int bad=r.returned!=(uint64_t)e||r.runtime;if(!e){bad|=r.out[0]!=expected.length;for(unsigned k=0;k<4;k++)bad|=r.out[k+1]!=(k<expected.length?expected.bytes[k]:0);}else for(unsigned k=0;k<5;k++)bad|=r.out[k]!=guard;if(bad){failures++;fprintf(stderr,"FAIL %s count=%llu reg=%llu width=%llu ret=%llu oracle=%u\n",name,(unsigned long long)count,(unsigned long long)reg,(unsigned long long)width,(unsigned long long)r.returned,(unsigned)e);}}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/x64-setcc-entry.nova","toolchain/ntasm-nova/x64_fixed.nova"};char*sources[2]={0};NtFInput inputs[2];for(unsigned i=0;i<2;i++){size_t n=0;sources[i]=loadf(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=sources[0]&&sources[1];CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,2,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){const char*names[]={"sete","setne","setb","setae","setbe","seta","sets","setns","setp","setnp","setl","setge","setle","setg","seto","setno"};for(unsigned n=0;n<16;n++)for(unsigned reg=0;reg<16;reg++)compare(&image,names[n],1,reg,8,1,3);compare(&image,"telepathy",1,0,8,1,3);compare(&image,"sete",0,0,8,1,3);compare(&image,"sete",1,0,64,1,3);compare(&image,"sete",1,16,8,1,3);compare(&image,"sete",1,0,8,0,3);compare(&image,"sete",1,0,8,1,4);Run short_=run(&image,"sete",1,0,8,1,3,4);cases++;CHECK(short_.returned==800&&short_.runtime==0&&short_.out[0]==guard,"short output transactional");}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<2;i++)free(sources[i]);printf("NTASM_NOVA_X64_SETCC checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
