#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;
static const uint64_t guard=UINT64_C(0xcccccccccccccccc);
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static char*load(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime,out[4];}Run;
static Run run(const NovaHostImage*i,const char*s,uint64_t words){Run r={.out={guard,guard,guard,guard}};NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t sh=nova_borrow_v2(&c,(void*)s,strlen(s),0),oh=nova_borrow_v2(&c,r.out,words*8,1);uint64_t a[]={sh,strlen(s),oh,words};r.returned=i->entry(&c,a,4);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void ok(const NovaHostImage*i,const char*n,const char*s,uint64_t sets,uint64_t predicates,uint64_t requires,uint64_t ensures){Run r=run(i,s,4);cases++;checks++;if(r.returned||r.runtime||r.out[0]!=sets||r.out[1]!=predicates||r.out[2]!=requires||r.out[3]!=ensures){failures++;fprintf(stderr,"FAIL ok %s ret=%llu out=%llu,%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
static void err(const NovaHostImage*i,const char*n,const char*s,uint64_t words,uint64_t code,uint64_t a,uint64_t b,int untouched){Run r=run(i,s,words);cases++;checks++;int bad=r.returned!=code||r.runtime;if(untouched)bad|=r.out[0]!=guard||r.out[1]!=guard;else bad|=r.out[0]==guard||r.out[1]==guard||r.out[2]!=a||(code==324&&r.out[3]!=b);if(bad){failures++;fprintf(stderr,"FAIL error %s ret=%llu out=%llu,%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/contracts-entry.nova","toolchain/ntasm-nova/contracts.nova","toolchain/ntasm-nova/effects.nova","toolchain/ntasm-nova/callable_names.nova","toolchain/ntasm-nova/semantics.nova","toolchain/ntasm-nova/parser.nova","toolchain/ntasm-nova/ast.nova","toolchain/ntasm-nova/lexer.nova"};char*sources[8]={0};NtFInput inputs[8];for(unsigned i=0;i<8;i++){size_t n=0;sources[i]=load(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=1;for(unsigned i=0;i<8;i++)if(!sources[i])all=0;CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,8,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){
const char*empty="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {}\nrequires {}\nensures {} {\nreturn 0\n}\n}\n";ok(&image,"empty",empty,2,0,1,1);
const char*allpred="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<user,u64> @rdi)->u64\neffects {}\nclobbers {}\nrequires {feature(sse2),non_null(p),canonical(p),stack_in(kernel),stack_aligned(16),msr_initialized(1),interrupts_enabled(),interrupts_disabled(),mapping_present(p),valid_user_return(p,p)}\nensures {} {\nreturn 0\n}\n}\n";ok(&image,"all",allpred,2,10,1,1);
const char*both="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<user,u64> @rdi)->u64\neffects {}\nclobbers {}\nrequires {non_null(p)}\nensures {canonical(p)} {\nreturn 0\n}\n}\n";ok(&image,"both",both,2,2,1,1);
const char*imported="module m\ntarget x86_64-nexora-none\nimport a.f as f: fn()->u64\neffects {}\nclobbers {}\nrequires {feature(sse2)}\nensures {}\n";ok(&image,"import",imported,2,1,1,1);
const char*unknown="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {}\nrequires {telepathy(1)} {\nreturn 0\n}\n}\n";err(&image,"unknown",unknown,4,323,1,0,0);
const char*qualified="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {}\nrequires {cpu.feature(sse2)} {\nreturn 0\n}\n}\n";err(&image,"qualified",qualified,4,323,2,0,0);
const char*missing="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {}\nrequires {feature()} {\nreturn 0\n}\n}\n";err(&image,"missing",missing,4,324,1,0,0);
const char*extra="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {}\nrequires {interrupts_enabled(1)} {\nreturn 0\n}\n}\n";err(&image,"extra",extra,4,324,0,1,0);
const char*two="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:ptr<user,u64> @rdi)->u64\neffects {}\nclobbers {}\nrequires {valid_user_return(p)} {\nreturn 0\n}\n}\n";err(&image,"two",two,4,324,2,1,0);
err(&image,"short",empty,3,800,0,0,1);err(&image,"invalid","target x86_64-nexora-none\n",4,800,0,0,1);
}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<8;i++)free(sources[i]);printf("NTASM_NOVA_CONTRACTS checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
