#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;static const uint64_t guard=UINT64_C(0xcccccccccccccccc);
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static char*loadf(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime,out[4];}Run;static Run run(const NovaHostImage*i,const char*s,uint64_t words){Run r={.out={guard,guard,guard,guard}};NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t sh=nova_borrow_v2(&c,(void*)s,strlen(s),0),oh=nova_borrow_v2(&c,r.out,words*8,1);uint64_t a[]={sh,strlen(s),oh,words};r.returned=i->entry(&c,a,4);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void ok(const NovaHostImage*i,const char*n,const char*s,uint64_t locals,uint64_t names,uint64_t calls,uint64_t literals){Run r=run(i,s,4);cases++;checks++;if(r.returned||r.runtime||r.out[0]!=locals||r.out[1]!=names||r.out[2]!=calls||r.out[3]!=literals){failures++;fprintf(stderr,"FAIL %s ret=%llu runtime=%llu out=%llu,%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.runtime,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
static void err(const NovaHostImage*i,const char*n,const char*s,uint64_t code,uint64_t reason){Run r=run(i,s,4);cases++;checks++;if(r.returned!=code||r.runtime||r.out[0]==0||r.out[1]==0||r.out[2]!=reason||r.out[3]!=0){failures++;fprintf(stderr,"FAIL %s ret=%llu runtime=%llu out=%llu,%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.runtime,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
static void bad(const NovaHostImage*i,const char*n,const char*s,uint64_t words){Run r=run(i,s,words);cases++;checks++;if(r.returned!=800||r.runtime||r.out[0]!=guard||r.out[1]!=guard){failures++;fprintf(stderr,"FAIL %s ret=%llu runtime=%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.runtime);}}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/initializer-types-entry.nova","toolchain/ntasm-nova/initializer_types.nova","toolchain/ntasm-nova/calls.nova","toolchain/ntasm-nova/refs.nova","toolchain/ntasm-nova/types.nova","toolchain/ntasm-nova/callable_names.nova","toolchain/ntasm-nova/semantics.nova","toolchain/ntasm-nova/parser.nova","toolchain/ntasm-nova/ast.nova","toolchain/ntasm-nova/lexer.nova"};char*sources[10]={0};NtFInput inputs[10];for(unsigned i=0;i<10;i++){size_t n=0;sources[i]=loadf(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=1;for(unsigned i=0;i<10;i++)if(!sources[i])all=0;CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,10,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){
const char*name_ok="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:u64 @rcx)->u64\neffects {}\nclobbers {} {\nlet x:u64=p\nreturn x\n}\n}\n";ok(&image,"name",name_ok,1,1,0,0);
const char*name_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:u32 @ecx)->u64\neffects {}\nclobbers {} {\nlet x:u64=p\nreturn x\n}\n}\n";err(&image,"name mismatch",name_bad,359,1);
const char*call_ok="module m\ntarget x86_64-nexora-none\nsection .text {\nfn value()->u64\neffects {}\nclobbers {} {\nreturn 1\n}\nfn f()->u64\neffects {}\nclobbers {} {\nlet x:u64=value()\nreturn x\n}\n}\n";ok(&image,"call",call_ok,1,0,1,0);
const char*call_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn value()->bool\neffects {}\nclobbers {} {\nreturn true\n}\nfn f()->u64\neffects {}\nclobbers {} {\nlet x:u64=value()\nreturn x\n}\n}\n";err(&image,"call mismatch",call_bad,359,1);
const char*literals="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nlet x:u64=1\nlet ready:bool=true\nreturn x\n}\n}\n";ok(&image,"literals delegated",literals,2,0,0,2);
const char*arithmetic="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:u64 @rcx)->u64\neffects {changes_flags}\nclobbers {} {\nlet x:u64=p+1\nreturn x\n}\n}\n";ok(&image,"one-level arithmetic",arithmetic,1,0,0,1);
const char*arithmetic_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:u32 @ecx)->u64\neffects {changes_flags}\nclobbers {} {\nlet x:u64=p+1\nreturn x\n}\n}\n";err(&image,"arithmetic mismatch",arithmetic_bad,359,2);
const char*nested="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:u64 @rcx)->u64\neffects {changes_flags}\nclobbers {} {\nlet x:u64=p+(1+2)\nreturn x\n}\n}\n";ok(&image,"nested grouped arithmetic",nested,1,0,0,1);
const char*precedence="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:u64 @rcx)->u64\neffects {changes_flags}\nclobbers {} {\nlet x:u64=p+1*2\nreturn x\n}\n}\n";ok(&image,"nested precedence",precedence,1,0,0,1);
const char*nested_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:u64 @rcx,in q:u32 @edx)->u64\neffects {changes_flags}\nclobbers {} {\nlet x:u64=p+(q+1)\nreturn x\n}\n}\n";err(&image,"nested mismatch",nested_bad,359,2);
const char*range_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:u8 @cl)->u8\neffects {changes_flags}\nclobbers {} {\nlet x:u8=p+(1+256)\nreturn x\n}\n}\n";err(&image,"nested literal range",range_bad,359,2);
const char*sibling="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nif true {\nlet x:u64=1\n}\nlet y:u64=x\nreturn y\n}\n}\n";err(&image,"sibling local not visible",sibling,360,1);
const char*self_ref="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nlet x:u64=x\nreturn x\n}\n}\n";err(&image,"self reference not visible",self_ref,360,1);
const char*shadow="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rcx)->u64\neffects {}\nclobbers {} {\nif true {\nlet x:u32=1\nlet y:u32=x\n}\nlet z:u64=x\nreturn z\n}\n}\n";ok(&image,"inner shadow then parameter fallback",shadow,3,2,0,1);
const char*future="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nlet y:u64=x\nlet x:u64=1\nreturn y\n}\n}\n";err(&image,"future declaration not visible",future,360,1);
const char*simple_local="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rcx)->u64\neffects {}\nclobbers {} {\nlet y:u64=x\nreturn y\n}\n}\n";ok(&image,"simple local name",simple_local,1,1,0,0);
const char*qualified_local="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in x:u64 @rcx)->u64\neffects {}\nclobbers {} {\nlet y:u64=bogus.x\nreturn y\n}\n}\n";err(&image,"qualified local rejected",qualified_local,360,3);
const char*unary_positive="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:u64 @rcx)->u64\neffects {}\nclobbers {} {\nlet x:u64=+p\nreturn x\n}\n}\n";ok(&image,"unary plus name",unary_positive,1,0,0,1);
const char*unary_bitnot="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:u64 @rcx)->u64\neffects {}\nclobbers {} {\nlet x:u64=~p\nreturn x\n}\n}\n";ok(&image,"unary bitnot name",unary_bitnot,1,0,0,1);
const char*unary_negative="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:i8 @cl)->i8\neffects {}\nclobbers {} {\nlet x:i8=-p\nreturn x\n}\n}\n";ok(&image,"unary negative signed name",unary_negative,1,0,0,1);
const char*negative_min="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->i8\neffects {}\nclobbers {} {\nlet x:i8=-128\nreturn x\n}\n}\n";ok(&image,"negative signed minimum",negative_min,1,0,0,1);
const char*negative_i16_min="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->i16\neffects {}\nclobbers {} {\nlet x:i16=-32768\nreturn x\n}\n}\n";ok(&image,"negative i16 minimum",negative_i16_min,1,0,0,1);
const char*negative_i32_min="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->i32\neffects {}\nclobbers {} {\nlet x:i32=-2147483648\nreturn x\n}\n}\n";ok(&image,"negative i32 minimum",negative_i32_min,1,0,0,1);
const char*negative_i64_min="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->i64\neffects {}\nclobbers {} {\nlet x:i64=-9223372036854775808\nreturn x\n}\n}\n";ok(&image,"negative i64 minimum",negative_i64_min,1,0,0,1);
const char*negative_i64_range="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->i64\neffects {}\nclobbers {} {\nlet x:i64=-9223372036854775809\nreturn x\n}\n}\n";err(&image,"negative i64 range",negative_i64_range,359,2);
const char*negative_range="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->i8\neffects {}\nclobbers {} {\nlet x:i8=-129\nreturn x\n}\n}\n";err(&image,"negative signed range",negative_range,359,2);
const char*negative_unsigned="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u8\neffects {}\nclobbers {} {\nlet x:u8=-1\nreturn x\n}\n}\n";err(&image,"negative unsigned mismatch",negative_unsigned,359,2);
const char*unary_bool="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nlet x:u64=~true\nreturn x\n}\n}\n";err(&image,"unary bool rejected",unary_bool,359,2);
const char*unary_nested="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f(in p:i8 @cl)->i8\neffects {}\nclobbers {} {\nlet x:i8=--p\nreturn x\n}\n}\n";ok(&image,"nested unary cardinality",unary_nested,1,0,0,1);
bad(&image,"short",name_ok,3);bad(&image,"invalid","target x86_64-nexora-none\n",4);
}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<10;i++)free(sources[i]);printf("NTASM_NOVA_INITIALIZER_TYPES checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
