#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;static const uint64_t guard=UINT64_C(0xcccccccccccccccc);
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static char*load(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime,out[4];}Run;
static Run run(const NovaHostImage*i,const char*s,uint64_t words){Run r={.out={guard,guard,guard,guard}};NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t sh=nova_borrow_v2(&c,(void*)s,strlen(s),0),oh=nova_borrow_v2(&c,r.out,words*8,1);uint64_t a[]={sh,strlen(s),oh,words};r.returned=i->entry(&c,a,4);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void ok(const NovaHostImage*i,const char*n,const char*s,uint64_t d,uint64_t c,uint64_t v){Run r=run(i,s,4);cases++;checks++;if(r.returned||r.runtime||r.out[0]!=d||r.out[1]!=c||r.out[2]!=v||r.out[3]){failures++;fprintf(stderr,"FAIL ok %s ret=%llu out=%llu,%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
static void err(const NovaHostImage*i,const char*n,const char*s,uint64_t words,uint64_t code,uint64_t cat,uint64_t missing,int untouched){Run r=run(i,s,words);cases++;checks++;int bad=r.returned!=code||r.runtime;if(untouched)bad|=r.out[0]!=guard||r.out[1]!=guard;else bad|=r.out[0]==guard||r.out[1]==guard||r.out[2]!=cat||r.out[3]!=missing;if(bad){failures++;fprintf(stderr,"FAIL error %s ret=%llu out=%llu,%llu,%llu,%llu\n",n,(unsigned long long)r.returned,(unsigned long long)r.out[0],(unsigned long long)r.out[1],(unsigned long long)r.out[2],(unsigned long long)r.out[3]);}}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/call-effects-entry.nova","toolchain/ntasm-nova/call_effects.nova","toolchain/ntasm-nova/calls.nova","toolchain/ntasm-nova/refs.nova","toolchain/ntasm-nova/contracts.nova","toolchain/ntasm-nova/effects.nova","toolchain/ntasm-nova/callable_names.nova","toolchain/ntasm-nova/semantics.nova","toolchain/ntasm-nova/parser.nova","toolchain/ntasm-nova/ast.nova","toolchain/ntasm-nova/lexer.nova"};char*sources[11]={0};NtFInput inputs[11];for(unsigned i=0;i<11;i++){size_t n=0;sources[i]=load(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=1;for(unsigned i=0;i<11;i++)if(!sources[i])all=0;CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,11,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){
const char*none="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nreturn 0\n}\n}\n";ok(&image,"none",none,1,0,0);
const char*atom_ok="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {privileged}\nclobbers {} {\nreturn 0\n}\nfn main()->u64\neffects {privileged,changes_flags}\nclobbers {} {\ncall leaf()\nreturn 0\n}\n}\n";ok(&image,"atom ok",atom_ok,2,1,1);
const char*atom_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {privileged}\nclobbers {} {\nreturn 0\n}\nfn main()->u64\neffects {}\nclobbers {} {\ncall leaf()\nreturn 0\n}\n}\n";err(&image,"atom bad",atom_bad,4,325,1,1,0);
const char*read_ok="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {reads_mem(user)}\nclobbers {} {\nreturn 0\n}\nfn main()->u64\neffects {reads_mem(user)}\nclobbers {} {\ncall leaf()\nreturn 0\n}\n}\n";ok(&image,"read ok",read_ok,2,1,1);
const char*read_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {reads_mem(user)}\nclobbers {} {\nreturn 0\n}\nfn main()->u64\neffects {reads_mem(kernel)}\nclobbers {} {\ncall leaf()\nreturn 0\n}\n}\n";err(&image,"read bad",read_bad,4,325,2,1,0);
const char*all_ok="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {reads_mem(user)}\nclobbers {} {\nreturn 0\n}\nfn main()->u64\neffects {reads_mem}\nclobbers {} {\ncall leaf()\nreturn 0\n}\n}\n";ok(&image,"all reads",all_ok,2,1,1);
const char*all_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {reads_mem}\nclobbers {} {\nreturn 0\n}\nfn main()->u64\neffects {reads_mem(user)}\nclobbers {} {\ncall leaf()\nreturn 0\n}\n}\n";err(&image,"scoped all",all_bad,4,325,2,62,0);
const char*write_bad="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {writes_mem(kernel)}\nclobbers {} {\nreturn 0\n}\nfn main()->u64\neffects {}\nclobbers {} {\ncall leaf()\nreturn 0\n}\n}\n";err(&image,"write",write_bad,4,325,3,2,0);
const char*import_ok="module m\ntarget x86_64-nexora-none\nimport a.f as f: fn()->u64\neffects {msr}\nclobbers {}\nsection .text {\nfn main()->u64\neffects {msr}\nclobbers {} {\ncall f()\nreturn 0\n}\n}\n";ok(&image,"import ok",import_ok,2,1,1);
const char*import_bad="module m\ntarget x86_64-nexora-none\nimport a.f as f: fn()->u64\neffects {msr}\nclobbers {}\nsection .text {\nfn main()->u64\neffects {}\nclobbers {} {\ncall f()\nreturn 0\n}\n}\n";err(&image,"import bad",import_bad,4,325,1,16,0);
const char*chain="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {reads_mem(user)}\nclobbers {} {\nreturn 0\n}\nfn mid()->u64\neffects {reads_mem(user)}\nclobbers {} {\ncall leaf()\nreturn 0\n}\nfn main()->u64\neffects {reads_mem(user)}\nclobbers {} {\ncall mid()\nreturn 0\n}\n}\n";ok(&image,"chain",chain,3,2,2);
const char*expression="module m\ntarget x86_64-nexora-none\nsection .text {\nfn leaf()->u64\neffects {changes_flags}\nclobbers {} {\nreturn 0\n}\nfn main()->u64\neffects {changes_flags}\nclobbers {} {\nreturn leaf()\n}\n}\n";ok(&image,"expression",expression,2,1,1);
err(&image,"short",none,3,800,0,0,1);err(&image,"invalid","target x86_64-nexora-none\n",4,800,0,0,1);
}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<11;i++)free(sources[i]);printf("NTASM_NOVA_CALL_EFFECTS checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
