#include "nova.h"
#include "nova/run_host.h"
#include "nova/runtime_v2.h"
#include "x64.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures,cases;
#define CHECK(c,m) do{checks++;if(!(c)){failures++;fprintf(stderr,"FAIL %s\n",m);}}while(0)
static const uint8_t guard=0xcc;
static char*loadf(const char*p,size_t*n){FILE*f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long z=ftell(f);fseek(f,0,SEEK_SET);char*b=z>=0?malloc((size_t)z+1):NULL;if(!b||fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return NULL;}fclose(f);b[z]=0;*n=(size_t)z;return b;}
typedef struct{uint64_t returned,runtime;uint8_t out[32];}Run;
static Run run(const NovaHostImage*i,const char*source,uint64_t features,uint64_t cpl,uint64_t words){Run r;memset(&r,0,sizeof r);memset(r.out,guard,sizeof r.out);NovaContextV2 c={0};CHECK(nova_context_init_v2(&c),"context init");uint64_t sh=nova_borrow_v2(&c,(void*)source,strlen(source),0),oh=nova_borrow_v2(&c,r.out,words,1);uint64_t a[]={sh,strlen(source),features,cpl,oh,words};r.returned=i->entry(&c,a,6);r.runtime=c.error;CHECK(nova_context_destroy_v2(&c),"context cleanup");return r;}
static void append(uint8_t*out,size_t*total,const char*name,NtX64Operand*operands,size_t count){NtX64Instruction encoded={0};NtX64Context context={1,3};CHECK(nt_x64_encode(name,operands,count,context,&encoded)==0,"oracle encode");memcpy(out+*total,encoded.bytes,encoded.length);*total+=encoded.length;}
static void basic(const NovaHostImage*i){const char*source="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nmov rax,rbx\nadd rax,1\nsub r8d,r9d\nreturn 0\n}\n}\n";uint8_t expected[31]={0};size_t total=0;NtX64Operand rr[2]={{.kind=NT_X64_REG,.width=64,.reg=0},{.kind=NT_X64_REG,.width=64,.reg=3}};append(expected,&total,"mov",rr,2);NtX64Operand ri[2]={{.kind=NT_X64_REG,.width=64,.reg=0},{.kind=NT_X64_IMM,.imm=1}};append(expected,&total,"add",ri,2);NtX64Operand sub[2]={{.kind=NT_X64_REG,.width=32,.reg=8},{.kind=NT_X64_REG,.width=32,.reg=9}};append(expected,&total,"sub",sub,2);Run r=run(i,source,1,3,32);cases++;CHECK(r.returned==0&&r.runtime==0&&r.out[0]==total&&!memcmp(r.out+1,expected,total),"basic AST lowering");}
static void error_(const NovaHostImage*i,const char*name,const char*source,uint64_t code,uint64_t words){Run r=run(i,source,1,3,words);cases++;int bad=r.returned!=code||r.runtime;for(unsigned k=0;k<words&&k<32;k++)bad|=r.out[k]!=guard;CHECK(!bad,name);}
int main(void){const char*paths[]={"toolchain/ntasm-nova/tests/x64-lower-basic-entry.nova","toolchain/ntasm-nova/x64_lower_fixed.nova","toolchain/ntasm-nova/x64_fixed.nova","toolchain/ntasm-nova/register_widths.nova","toolchain/ntasm-nova/parser.nova","toolchain/ntasm-nova/ast.nova","toolchain/ntasm-nova/lexer.nova"};char*sources[7]={0};NtFInput inputs[7];for(unsigned i=0;i<7;i++){size_t n=0;sources[i]=loadf(paths[i],&n);inputs[i]=(NtFInput){paths[i],sources[i],n};}int all=1;for(unsigned i=0;i<7;i++)if(!sources[i])all=0;CHECK(all,"sources load");NtArtifact a={0};int compiled=all&&nova_compile_many_v2(inputs,7,&a);CHECK(compiled,"modules compile");if(!compiled)fprintf(stderr,"E%u %zu:%zu %s\n",a.error.code,a.error.line,a.error.column,a.error.message);NovaHostImage image={0};CHECK(compiled&&nova_host_map(&a,&image),"image maps");if(image.memory){basic(&image);const char*mismatch="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nmov rax,ebx\nreturn 0\n}\n}\n";error_(&image,"width mismatch",mismatch,403,32);const char*nested="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nadd rax,1+2\nreturn 0\n}\n}\n";error_(&image,"nested expression",nested,409,32);const char*high8="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nmov ah,bl\nreturn 0\n}\n}\n";error_(&image,"high8 unsupported",high8,406,32);const char*short_="module m\ntarget x86_64-nexora-none\nsection .text {\nfn f()->u64\neffects {}\nclobbers {} {\nmov rax,rbx\nreturn 0\n}\n}\n";error_(&image,"short output",short_,800,2);error_(&image,"invalid tree","target x86_64-nexora-none\n",800,32);}if(image.memory)nova_host_unmap(&image);if(compiled)nt_artifact_free(&a);for(unsigned i=0;i<7;i++)free(sources[i]);printf("NTASM_NOVA_X64_LOWER_BASIC checks=%u failures=%u cases=%u\n",checks,failures,cases);return failures?1:0;}
